<?php
/*echo 'This is view of Paginator';
echo $this->currentUrl;*/

	$linkStart 		= $this->currentUrl . '/page/' . $this->first;
	
	//$linkPrevious = '#';
	if(isset($this->previous)){
		$linkPrevious 	= $this->currentUrl . '/page/' . $this->previous;
	}
	//$linkNext = '#';
	if(isset($this->next)){
		$linkNext 		= $this->currentUrl . '/page/' . $this->next;
	}
	
	$linkEnd 		= $this->currentUrl . '/page/' . $this->last;
	
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current == $key){
			$strPage .= '<b>' . $key .'</b>';
		}else{
			$linkPage = $this->currentUrl . '/page/' . $key;
			$strPage .= '<a href="' . $linkPage . '">' . $key .'</a>'; 
		}
	}

	$page = 'Page ' . $this->current .' Of ' . $this->last;
?>
<div class="links">
	<a href="<?php echo $linkStart;?>" title="Start">|&lt;</a>
	<?php if(isset($linkPrevious) && $linkPrevious) { ?>
		<a href="<?php echo $linkPrevious;?>" title="Prev" >&lt;</a>
	<?php }?>
	<?php echo $strPage;?>
	<?php if(isset($linkNext) && $linkNext) { ?>
		<a href="<?php echo $linkNext;?>" title="Next" >&gt;</a>
	<?php }?>
	<a href="<?php echo $linkEnd;?>" title="End" >&gt;|</a>
</div>
<div class="results"><?php echo $page;?></div>
