<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->headScript() ?>
</head>
<body>
<div id="header">
  <div id="header-content">
  	<!--<a href="#"><img src="<?php echo HTTP_IMAGES . '/logo/logo.png'; ?>" title="" alt="" /></a>-->
  </div>
  <?php echo $this->blkFrontMenu();?>
</div>
<div id="container">
<div id="notification"></div>