<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br>Save</a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl($this->currentController . '/index');?>"><?php echo $this->cmsTranslator('product_home');?></a>
	<a href="#">??</a>
</div>
<div class="content">
	<form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
	<div id="languages" class="htabs">
	<?php foreach ($this->languages as $key => $value) { ?>
	<?php $language = explode('|', $value);?>
	<a href="#language_<?php echo $key; ?>">
		<img src="<?php echo HTTP_IMAGES . '/flags/' . $language[0] . '.png'; ?>" title="<?php echo $language[1]; ?>" />
		<?php echo $language[1]; ?>
	</a>
	<?php } ?>
	</div>
	<?php foreach ($this->languages as $language => $value) { ?>
	<div id="language_<?php echo $language; ?>">    
      <table class="form">
        <tr>
          <td><span class="required">*</span> Tên sản phẩm:</td>
          <td><input type="text" name="product_description[<?php echo $language; ?>][name]" size="100" value="<?php echo isset($this->Item['product_description'][$language]['name']) ? $this->Item['product_description'][$language]['name'] : '';?>" /></td>
        </tr>
        <tr>
          <td>Meta keyword:</td>
          <td><textarea name="product_description[<?php echo $language; ?>][meta_keywords]" cols="40" rows="5"><?php echo isset($this->Item['product_description'][$language]['meta_keywords']) ? $this->Item['product_description'][$language]['meta_keywords'] : '';?></textarea></td>
        </tr>
        <tr>
          <td>Meta Description:</td>
          <td><textarea name="product_description[<?php echo $language; ?>][meta_description]" cols="40" rows="5"><?php echo isset($this->Item['product_description'][$language]['meta_description']) ? $this->Item['product_description'][$language]['meta_description'] : '';?></textarea></td>
        </tr>
        <tr>
          <td>Mô tả:</td>
          <td><textarea name="product_description[<?php echo $language; ?>][description]" id="description_<?php echo $language; ?>"><?php echo isset($this->Item['product_description'][$language]['description']) ? $this->Item['product_description'][$language]['description'] : '';?></textarea></td>
        </tr>
      </table>
	</div>
	<?php } ?>
      <table class="form">
        <tr>
          <td>Số lượng: </td>
          <td><input type="text" name="quantity" value="<?php echo $this->Item['quantity'];?>" size="4" /></td>
        </tr>
        <tr>
          <td>Giá:</td>
          <td><input type="text" name="price" value="<?php echo $this->Item['price'];?>" size="4" /></td>
        </tr>
        <tr>
          <td>Hình đại diện:</td>
          <td valign="top">
          <?php
           if ($this->Item['image'] && file_exists(PUBLIC_PATH . '/images/' . $this->Item['image'])) {
				$image = $this->cmsImageResize($this->Item['image'], 100, 100);
			} else {
				$image = $this->cmsImageResize('no_image.jpg', 100, 100);
			}
          ?>
          <div class="image"><img id="thumb" alt="" src="<?php echo $image;?>">
          <input type="hidden" id="image" value="<?php echo $this->Item['image'];?>" name="image">
          <br>
          <a onclick="image_upload('image', 'thumb');">Browse Files</a>&nbsp;&nbsp;|&nbsp;&nbsp;
          <a onclick="$('#thumb').attr('src', '<?php echo $this->cmsImageResize('no_image.jpg', 100, 100);?>'); $('#image').attr('value', '');">Clear Image</a></div></td>
        </tr>
        <tr>
          <td>Sắp xếp:</td>
          <td><input type="text" name="sort_order" value="<?php echo $this->Item['sort_order'];?>" size="1" /></td>
        </tr>
		<tr>
		   <td>Trạng thái: </td>
           <td><select name="status">
                  <?php if ($this->Item['status']) { ?>
                  <option value="1" selected="selected">Mở</option>
                  <option value="0">Tắt</option>
                  <?php } else { ?>
                  <option value="1">Mở</option>
                  <option value="0" selected="selected">Tắt</option>
                  <?php } ?>
                </select></td>
        </tr>
      </table>
    </form>
	<!-- khởi tạo editor -->
	<?php 
		$editor = array();
		foreach ($this->languages as $language => $value) {
			$editor[] = 'description_' . $language;
		}
		echo $this->cmsEditor($editor, array());
	?>	
	<!-- Ngày tháng -->
	<script type="text/javascript" src="<?php echo HTTP_PUBLIC . '/javascript/jquery/ui/jquery-ui-timepicker-addon.js';?>"></script> 
	<script type="text/javascript">
	$('.date').datepicker({dateFormat: 'yy-mm-dd'});
	$('.datetime').datetimepicker({
		dateFormat: 'yy-mm-dd',
		timeFormat: 'h:m'
	});
	$('.time').timepicker({timeFormat: 'h:m'});
	</script>
	<script type="text/javascript">
	function image_upload(field, thumb) {
		$('#dialog').remove();
		
		$('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo HTTP_SERVER ;?>/admin/filemanager?field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
		
		$('#dialog').dialog({
			title: 'Quản lý hình ảnh',
			close: function (event, ui) {
				if ($('#' + field).attr('value')) {
					$.ajax({
						url: '<?php echo HTTP_SERVER ;?>/admin/filemanager/image?image=' + encodeURIComponent($('#' + field).val()),
						dataType: 'text',
						success: function(data) {
							$('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
						}
					});
				}
			},	
			bgiframe: false,
			width: 800,
			height: 400,
			resizable: false,
			modal: true
		});
	};
	</script> 
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				<?php foreach ($this->languages as $language => $value) { ?>
					"product_description[<?php echo $language; ?>][name]": {
			  		required: true,
			  		minlength: 3,
			  		maxlength: 200,
			  	},
			  	<?php } ?>
		    },
		    messages: {		    	
		    	<?php foreach ($this->languages as $language => $value) { ?>
		    		"product_description[<?php echo $language; ?>][name]": {
		        	required: "user_user_name_required",
					minlength: "user_user_name_minlength",
					maxlength: "user_user_name_maxlength",
				},
			  	<?php } ?>
			}
		});
	});
	</script>
	<script type="text/javascript">
		$('#languages a').tabs();
	</script> 
</div>
</div>