<fieldset>
<div class='buttongroup'>
<input type='button' value='Save'>
<input type='button' value='Cancel'>
</div>
<div class='header'>Article Manager - Config</div>
</fieldset>
<fieldset class='config-field'>
<legend>Configuration</legend>
<table class='config-table'>
	<tbody>
	<tr class='oddrow'>
		<td>Show Authorized Links</td>
		<td><?php echo $this->form->showauthorizedlink;?>
		</td>
	</tr>
	<tr class='evenrow'>
		<td>Show Article Title</td>
		<td><?php echo $this->form->showarticletitle;?>
		</td>
	</tr>
	<tr class='oddrow'>
		<td>Title Linkable</td>
		<td><?php echo $this->form->titlelinkable;?>
		</td>
	</tr>
	<tr class='evenrow'>
		<td>Show Nevigation</td>
		<td><?php echo $this->form->shownevigation;?>
		</td>
	</tr>
		<tr class='oddrow'>
		<td>Read more... Link</td>
		<td><?php echo $this->form->showreadmore;?>
		<td>
	</tr>
	<tr class='evenrow'>
		<td>Show Intro Text</td>
		<td><?php echo $this->form->showintro;?>
		</td>
	</tr>
	<tr class='separator'>
		<td></td>
		<td>
		</td>
	</tr>
	<tr class='evenrow'>
		<td>Show Section Name</td>
		<td><?php echo $this->form->showsection;?>
		</td>
	</tr>
	<tr class='oddrow'>
		<td>Section Title Linkable</td>
		<td><?php echo $this->form->sectionlinkable;?>
		</td>
	</tr>
		<tr class='evenrow'>
		<td>Show Category Name</td>
		<td><?php echo $this->form->showcategory;?>
		</td>
	</tr>
		<tr class='oddrow'>
		<td>Category Title Linkable</td>
		<td><?php echo $this->form->categorylinkable;?>
		</td>
	</tr >
		<tr class='separator'>
		<td></td>
		<td>
		</td>
	</tr>
		<tr class='oddrow'>
		<td>Show Author Name</td>
		<td><?php echo $this->form->showauthor;?>
		</td>
	</tr>
		<tr class='evenrow'>
		<td>Author Name Linkable</td>
		<td><?php echo $this->form->authorlinkable;?>
		</td>
	</tr>
		<tr class='oddrow'>
		<td>Show Created Date</td>
		<td><?php echo $this->form->showcreatedate;?>
		</td>
	</tr>
		<tr class='evenrow'>
		<td>Show Modified Date</td>
		<td><?php echo $this->form->showmodifydate;?>
		</td>
	</tr>
		<tr class='oddrow'>
		<td>Show Hits</td>
		<td><?php echo $this->form->showhits;?>
		</td>
	</tr>
	</tbody>
</table>
</fieldset>