<div id='toolbar-box2'>
	<div class='bia-tren'>
			<div class='bia-tren'>
				<div class='bia-tren'></div>
			</div>
	</div>
	<div class='bia-giua'>
		<div class='toolbar3' align='center'>
			<input type='submit' value='Save'></input>
			<input type='submit' value='Cancel'></input>
		</div>
		<div class='header'>Article Manager - Copy Article</div>
	</div>
	<div class='bia-duoi'>
		<div class='bia-duoi'>
			<div class='bia-duoi'></div>
		</div>
	</div>
</div>
<div id='Content-box'>
	<div class='bia-tren'>
			<div class='bia-tren'>
				<div class='bia-tren'></div>
			</div>
	</div>
	<div class='bia-giua'>
		<div class='article-list'><?php echo $this->form->articlelist;?></div>
		<div class='cate-list'><?php echo $this->form->catelist; ?>
		</div>
	</div>
	<div class='bia-duoi'>
		<div class='bia-duoi'>
			<div class='bia-duoi'></div>
		</div>
	</div>
</div>