<h3>Article Manager</h3> 
<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/article/sectionnew")?>">Section New</a>{by TuTM}<br>
	<a href="<?php echo $this->baseUrl("/admin/article/sectionedit")?>">Section Edit</a>{by TuTM}<br>
	<a href="<?php echo $this->baseUrl("/admin/article/sectionmanager")?>">Section Manager </a>{By DungDV}<br>
	<a href="<?php echo $this->baseUrl("/admin/article/articlelist")?>">Article List</a>{by DucNH}<br>	
	<a href="<?php echo $this->baseUrl("/admin/article/articleedit")?>">Article Edit</a>{By DungDV}<br>	
	<a href="<?php echo $this->baseUrl("/admin/article/frontpagemanager")?>">Front Page Manager</a>{By DungDV}<br>
</div>

