<h2>Hello, this is Article Manager View page</h2>
<!-- Vùng DIV thử nghiệm -->
<div id='toolbar-box2'>
	<div class='bia-tren'>
			<div class='bia-tren'>
				<div class='bia-tren'></div>
			</div>
	</div>
	<div class='bia-giua'>
		<div id='toolbar2' class='toolbar2'>
			<table class='toolbar'>
			<tbody>
			<tr>
				<td class='button'><span class="icon-32-publish"></span>Publish</td>
				<td class='button'><span class="icon-32-unpublish"></span>Unpublish</td>
				<td class='button'><span class="icon-32-move"></span>Move</td>
				<td class='button'><span class="icon-32-copy"></span>Copy</td>
				<td class='button'><span class="icon-32-trash"></span>Trash</td>
				<td class='button'><span class="icon-32-edit"></span>Edit</td>
				<td class='button'><span class="icon-32-new"></span>New</td>
				<td class='button'><span class="icon-32-config"></span>Parameters</td>
				<td class='button'><span class="icon-32-help"></span>Help</td>
			</tr>
			</tbody>
			</table>
		</div>
		<div class='header'>Article Manager</div>
	</div>
	<div class='bia-duoi'>
		<div class='bia-duoi'>
			<div class='bia-duoi'></div>
		</div>
	</div>
</div>
<br>
<!-- Article List GridView -->
<div id='ArticleList'>
	<div class='bia-tren'>
	<div class='bia-tren'><div class='bia-tren'></div></div>
	</div>
	<div class='bia-giua'>
		<table>
		<tr>
			<td width=100% >
				<?php echo $this->form->filter; echo $this->form->Go; echo $this->form->Reset;?>
			</td>
			<td nowrap='nowrap'>
				<?php echo $this->form->testcheckbox; 
					echo $this->form->sectionSelect; 
					echo $this->form->categorySelect; 
					echo $this->form->authorSelect; 
					echo $this->form->stateSelect;
				?>
			</td>
		</tr>
		</table>
		<table class='adminlist'>
		<thead>
			<?php echo $this->form->fuckingname;?>
		</thead>
		<tbody>
			<?php $this->form->echoarticles();?>
		</tbody>
		<tfoot>
		<tr>
			<td colspan='15' align='center'>
			<?php echo $this->form->nevigationbar;?>
			</td>
		</tr>
		</tfoot>
		</table>
	</div>
	<div class='bia-duoi'><div class='bia-duoi'><div class='bia-duoi'></div></div></div>
</div>