<div id="content">
<div class="main">
	<div class="group">
	<!-- Begin Code -->
	
	<!-- End Code -->
	</div>
	<div class="group">
	<!-- Begin Code -->
	
	<!-- End Code -->
	</div>
</div>
<script type="text/javascript">
function ChangeStyleIcon(div,action)
{
	switch (action)
	{
		case 1:
			document.getElementById(div).style.border = "1px #ff0000 solid";
			break;
		case 2:
			document.getElementById(div).style.border = "1px #EAEAEA solid";
			break;
		default:
			document.getElementById(div).style.border = "1px #2F97FF solid";
	}
}
</script> 
</div>