<h4>Language Manager</h4>
<form action="index.php" method="post" name="adminForm">
<table border="1">
	<tr>
		<th width="20">#</th>
		<th width="30">&nbsp;</th>
		<th width="25%" class="title">Language Name</th>
		<th width="5%">Default</th>
		<th width="10%">Version</th>
		<th width="10%">Date</th>
		<th width="20%">Author</th>
		<th width="25%">Author E-mail</th>
	</tr>
	<tbody>
		<tr class="row0">
			<td width="20">1</td>
			<td width="20"><input type="radio" id="cb0" name="cid[]"
				value="en-GB" onclick="isChecked(this.checked);" /></td>
			<td width="25%">English(United Kingdom)</td>
			<td width="5%" align="center">&nbsp;</td>
			<td align="center">1.5.15</td>
			<td align="center">2009-10-27</td>
			<td align="center">Joomla! Project</td>
			<td align="center">admin@joomla.org</td>
		</tr>
		<tr class="row0">
			<td width="20">2</td>
			<td width="20"><input type="radio" id="cb1" name="cid[]"
				value="vi-VN" onclick="isChecked(this.checked);" /></td>
			<td width="25%">Vietnamese</td>
			<td width="5%" align="center"><img src="" alt="Default"></td>
			<td align="center">1.5.23</td>
			<td align="center">10-13-2010</td>
			<td align="center">BuaXua.vn</td>
			<td align="center">contact@buaxua.vn</td>
		</tr>
	</tbody>

</table>
</form>

