<div id="content">
<div class="toolbox">
	<div class="left">Member :: Group manager :: List</div>
	<div class="right">
	<!-- 
		<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>"/><br>Add New</a></div>
		<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active Items</a></div>
		<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>"/><br>Inactive Items</a></div>
		<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-delete.png';?>"/><br>Delete</a></div>
	 -->
	</div>
</div>
<div class="main">
	<div class="group">
		<div class="title">Hệ thống</div>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_01',2)" onmouseover="ChangeStyleIcon('icon_main_01',1)" id="icon_main_01" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_02',2)" onmouseover="ChangeStyleIcon('icon_main_02',1)" id="icon_main_02" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_03',2)" onmouseover="ChangeStyleIcon('icon_main_03',1)" id="icon_main_03" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_04',2)" onmouseover="ChangeStyleIcon('icon_main_04',1)" id="icon_main_04" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_05',2)" onmouseover="ChangeStyleIcon('icon_main_05',1)" id="icon_main_05" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_06',2)" onmouseover="ChangeStyleIcon('icon_main_06',1)" id="icon_main_06" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_07',2)" onmouseover="ChangeStyleIcon('icon_main_07',1)" id="icon_main_07" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_08',2)" onmouseover="ChangeStyleIcon('icon_main_08',1)" id="icon_main_08" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_09',2)" onmouseover="ChangeStyleIcon('icon_main_09',1)" id="icon_main_09" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_10',2)" onmouseover="ChangeStyleIcon('icon_main_10',1)" id="icon_main_10" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_11',2)" onmouseover="ChangeStyleIcon('icon_main_11',1)" id="icon_main_11" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_12',2)" onmouseover="ChangeStyleIcon('icon_main_12',1)" id="icon_main_12" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_13',2)" onmouseover="ChangeStyleIcon('icon_main_13',1)" id="icon_main_13" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_14',2)" onmouseover="ChangeStyleIcon('icon_main_14',1)" id="icon_main_14" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_15',2)" onmouseover="ChangeStyleIcon('icon_main_15',1)" id="icon_main_15" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_16',2)" onmouseover="ChangeStyleIcon('icon_main_16',1)" id="icon_main_16" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_17',2)" onmouseover="ChangeStyleIcon('icon_main_17',1)" id="icon_main_17" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_18',2)" onmouseover="ChangeStyleIcon('icon_main_18',1)" id="icon_main_18" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_19',2)" onmouseover="ChangeStyleIcon('icon_main_19',1)" id="icon_main_19" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_20',2)" onmouseover="ChangeStyleIcon('icon_main_20',1)" id="icon_main_20" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
	</div>
	<div class="group">
		<div class="title">Hệ thống</div>
		<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_21',2)" onmouseover="ChangeStyleIcon('icon_main_21',1)" id="icon_main_21" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_22',2)" onmouseover="ChangeStyleIcon('icon_main_22',1)" id="icon_main_22" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_23',2)" onmouseover="ChangeStyleIcon('icon_main_23',1)" id="icon_main_23" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_24',2)" onmouseover="ChangeStyleIcon('icon_main_24',1)" id="icon_main_24" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_25',2)" onmouseover="ChangeStyleIcon('icon_main_25',1)" id="icon_main_25" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_26',2)" onmouseover="ChangeStyleIcon('icon_main_26',1)" id="icon_main_26" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_27',2)" onmouseover="ChangeStyleIcon('icon_main_27',1)" id="icon_main_27" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_28',2)" onmouseover="ChangeStyleIcon('icon_main_28',1)" id="icon_main_28" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_29',2)" onmouseover="ChangeStyleIcon('icon_main_29',1)" id="icon_main_29" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
    	<a onclick="window.open('http://localhost/hera.vn/');">
        	<div onmouseout="ChangeStyleIcon('icon_main_30',2)" onmouseover="ChangeStyleIcon('icon_main_30',1)" id="icon_main_30" class="icon_main">
            	<img border="0" src="<?php echo HTTP_PUBLIC . '/skins/admin/images';?>/home-icon.png">
                <div class="text_icon_main">Trang chủ</div>
        	</div>
    	</a>
	</div>
</div>
<script type="text/javascript">
function ChangeStyleIcon(div,action)
{
	switch (action)
	{
		case 1:
			document.getElementById(div).style.border = "1px #ff0000 solid";
			break;
		case 2:
			document.getElementById(div).style.border = "1px #EAEAEA solid";
			break;
		default:
			document.getElementById(div).style.border = "1px #2F97FF solid";
	}
}
</script> 
</div>