<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php
		//1. Add new - link
		$btnAddNew = $this->cmsButton(
						'Add new',
						$this->baseUrl($this->currentController . '/add'),
						HTTP_IMAGES . '/icon/icon-32-new.png',
						'link'
					);
		//2. Active - submit
		$btnActive = $this->cmsButton(
						'Active Items',
						$this->baseUrl($this->currentController . '/status/type/1'),											
						HTTP_IMAGES . '/icon/icon-32-active.png',
						'submit'
					);
		//3. Inactive- submit
		$btnInactive = $this->cmsButton(
						'Inactive Items',
						$this->baseUrl($this->currentController . '/status/type/0'),										
						HTTP_IMAGES . '/icon/icon-32-inactive.png',
						'submit'
					);

		//4. Delete - submit
		$btnDelete = $this->cmsButton(
						'Delete Items',
						$this->baseUrl($this->currentController . '/multi-delete'),
						HTTP_IMAGES . '/icon/icon-32-delete.png',
						'submit'
					);	
		
	?>
	<div class="right"><?php echo $btnAddNew;?><?php echo $btnActive;?><?php echo $btnInactive;?><?php echo $btnDelete;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo HTTP_SERVER . '/admin/userpermission/index/';?>">Group Manager</a>
	<a href="<?php echo HTTP_SERVER . '/admin/user/index/';?>">Member Manager</a>
</div>
<div class="content">
	<?php 		
		$filter = $this->arrParam['filter'];
		$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
		$sortGroupName 	= $this->cmsLinkSort('Group Name', 'ug.name', $filter, $action_link);
		
		$sortID 	= $this->cmsLinkSort('ID','ug.user_group_id', $filter, $action_link);
											
		$sortMember	= $this->cmsLinkSort('Member', 'members', $filter, $action_link);
		
		$sortStatus	= $this->cmsLinkSort('Status', 'ug.status', $filter, $action_link);																				
	
		$sortOrder	= $this->cmsLinkSort('Order', 'ug.sort_order', $filter, $action_link);	
																		
	?>
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
      <table class="list">
        <thead>
          <tr>
            <td width="1" style="text-align: center;">
            	<input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" />
            </td>            
            <td class="left"><?php echo $sortID;?></td>
            <td class="left"><?php echo $sortGroupName;?></td>
            <td class="center"><?php echo $sortMember;?></td>
            <td class="center"><?php echo $sortStatus;?></td>
            <td class="center"><?php echo $sortOrder;?></td>
            <td class="right">Control</td>
          </tr>
        </thead>
        <tbody>
          <tr class="filter">
            <td></td>
            <td></td>
            <td><input type="text" name="filter_name" value=""/></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="right">
            	<a class="button" onclick="OnSubmitForm('<?php echo $this->baseUrl($this->currentController . '/filter/type/search/key/1'); ?>')"><span>filter</span></a>
            	<a class="button" onclick="OnSubmitForm('<?php echo $this->baseUrl($this->currentController . '/filter/type/search/key/0'); ?>')"><span>clear</span></a>
            </td>
          </tr>
          <?php if ($this->Items) { ?>
          <?php foreach($this->Items as $key => $val){
          	
				$selected = $this->formCheckbox('selected[]', $val['user_group_id']);
				
				$name = $val['name'];
				
				if($val['status'] == 1){	
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/user_group_id/' . $val['user_group_id']);											
					$status = $this->cmsIconButton('Active', HTTP_IMAGES. '/icon/icon_16_active.png', $linkStatus);
				}else{
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/user_group_id/' . $val['user_group_id']);
					$status = $this->cmsIconButton('INactive', HTTP_IMAGES. '/icon/icon_16_inactive.png', $linkStatus);
				}
										
				$linkInfo = $this->baseUrl($this->currentController . '/info/user_group_id/' . $val['user_group_id']);											
				$btnInfo = $this->cmsIconButton('View Item', HTTP_IMAGES. '/icon/icon_16_info.png', $linkInfo);
				$linkEdit = $this->baseUrl($this->currentController . '/edit/user_group_id/' . $val['user_group_id']);
				$btnEdit = $this->cmsIconButton('Edit Item', HTTP_IMAGES. '/icon/icon_16_edit.png', $linkEdit);
				$linkDelete	= $this->baseUrl($this->currentController . '/delete/user_group_id/' . $val['user_group_id']);
				$btnDelete = $this->cmsIconButton('Delete Item', HTTP_IMAGES. '/icon/icon_16_del.png', $linkDelete);
				$strIconButton = $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
		  ?>
          <tr>            
            <td align="center"><?php echo $selected;?></td>
            <td align="left"><?php echo $val['user_group_id'];?></td>
            <td align="left"><?php echo $name;?></td>
            <td align="center"><?php echo $val['members'];?></td>
            <td align="center"><?php echo $status;?></td>
            <td align="center"><?php echo $val['sort_order'];?></td>
 			<td align="right"><?php echo $strIconButton;?></td>
          </tr>
          <?php } ?>
          <?php } else { ?>
          <tr>
            <td class="center" colspan="7">Không có kết quả</td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
    </form>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
</div>
</div>