<div id="content">
	<div class="toolbox">
		<div class="left">Quản lý :: Tin Tức - Sự Kiện</div>
		<div class="right">
			<div><a href="<?php echo $this->baseUrl("/admin/news/new")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>"/><br>New</a></div>
			<div><a href="<?php echo $this->baseUrl("/admin/news/edit")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>"/><br>Edit</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active</a></div>			
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-delete.png';?>"/><br>Delete</a></div>
		</div>
	</div>
	<div class="breadcrumb">
		<a href="#">...</a>
		<a href="#">...</a>
	</div>
	<table border="1" width="1200" cellpadding="1" cellspacing="0">
	<tr style="font-weight: bold; text-align: center; background-color: #E7E7E7;"> <td width="50"> ID </td> <td width="350">Tiêu đề</td><td width="70">Lượt xem</td> <td width="50">Thứ tự</td> <td width="50">Trạng thái</td> <td width="200">Người tạo</td> <td width="150">Ngày thêm</td> <td width="150">Ngày sửa</td> <td>Thao tác</td></tr>
	<?php 
	foreach($this->news as $news){

		echo '<tr><td align="center" >'.$news["news_id"];
		echo '</td> <td>'.$news['title'];
		
		//echo "</td> <td>".$news["image"];
		echo '</td> <td align="center">'.$news['viewed'];
		echo '</td> <td align="center">'.$news['sort_order'];
		echo '</td> <td align="center">'.$news['status'];
		echo '</td> <td align="center">'.$news['author'];
		echo '</td> <td align="center">'.$news["date_added"];
		echo '</td> <td align="center">'.$news["date_modified"];
echo '</td><td><a href='.$this->baseUrl("/admin/news/edit")."?news_id=".$news['news_id'].'>Sửa</a>  &nbsp&nbsp  <a href='.$this->baseUrl("admin/news/delete")."?news_id=".$news['news_id'].'>Xóa</a> &nbsp&nbsp <a href='.$this->baseUrl("admin/news/newsnew").'>Active</a></td></tr>';
}
?>

	</table>
	
</div>


