<div id="content">
<div class="toolbox">
<div class="left">Quản lý :: Tin Tức - Sự Kiện</div>
<div class="right">
<div><a href="<?php echo $this->baseUrl("/admin/news/new")?>"><img	alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>" /><br>
New</a></div>
<div><a href="<?php echo $this->baseUrl("/admin/news/edit")?>"><img	alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>" /><br>
Edit</a></div>
<div><a href=""><img alt=""	src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>" /><br>
Active</a></div>
<div><a href=""><img alt=""	src="<?php echo HTTP_IMAGES . '/icon/icon-32-delete.png';?>" /><br>
Delete</a></div>
</div>
</div>
<div class="breadcrumb"><a href="#">...</a> <a href="#">...</a></div>
<table class="list" width="" cellpadding="1" cellspacing="0">
<thead>
	<tr>
		<td>ID</td>
		<td >Tiêu đề</td>
		<td>Lượt xem</td>
		<td>Thứ tự</td>
		<td>Trạng thái</td>
		<td>Người tạo</td>
		<td>Ngày thêm</td>
		<td>Thao tác</td>
	</tr>
	</thead>
	<tbody>
	<?php
foreach ($this->news as $news){		
		echo '<tr><td align="center" >'.$news["news_id"];
		echo '</td> <td>'.$news['title'];
		
		//echo "</td> <td>".$news["image"];
		echo '</td> <td align="center">'.$news['viewed'];
		echo '</td> <td align="center">'.$news['sort_order'];
		echo '</td> <td align="center">'.$news['status'];
		echo '</td> <td align="center">'.$news['author'];
		echo '</td> <td align="center">'.$news["date_added"];

echo '</td><td class="left"><a href='.$this->baseUrl("/admin/news/edit")."?news_id=".$news['news_id'].'>Sửa</a>  &nbsp  <a href='.$this->baseUrl("admin/news/delete")."?news_id=".$news['news_id'].'>Xóa</a> &nbsp <a href='.$this->baseUrl("admin/news/newsnew").'>Active</a></td></tr>';
}
?>
	</tbody>
	</table>

</div>


