<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php
	date_default_timezone_set('Asia/Saigon');	
		//1. Add new - link
		$btnAddNew = $this->cmsButton(
						'Add',
						$this->baseUrl($this->currentController . '/add'),
						HTTP_IMAGES . '/icon/icon-32-new.png',
						'link'
					);
		//2. Active - submit
		$btnActive = $this->cmsButton(
						'Active Items',
						$this->baseUrl($this->currentController . '/status/type/1'),											
						HTTP_IMAGES . '/icon/icon-32-active.png',
						'submit'
					);
		//3. Inactive- submit
		$btnInactive = $this->cmsButton(
						'Inactive Items',
						$this->baseUrl($this->currentController . '/status/type/0'),										
						HTTP_IMAGES . '/icon/icon-32-inactive.png',
						'submit'
					);

		//4. Delete - submit
		$btnDelete = $this->cmsButton(
						'Delete Items',
						$this->baseUrl($this->currentController . '/multi-delete'),
						HTTP_IMAGES . '/icon/icon-32-delete.png',
						'submit'
					);	
		
	?>
	<div class="right"><?php echo $btnAddNew;?><?php echo $btnActive;?><?php echo $btnInactive;?><?php echo $btnDelete;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/product/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl($this->currentController . '/product/index/');?>">????</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
      <table class="list">
        <thead>
          <tr>
            <td width="1" style="text-align: center;">
            	<input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" />
            </td>            
            <td class="left">ID</td>
            <td class="left">Tên sản phẩm</td>
            <td class="center">Trạng thái</td>
            <td class="center">Thứ tự</td>
            <td class="center">Ngày nhập</td>
            <td class="right">Hành động</td>
          </tr>
        </thead>
        <tbody>
          <?php if ($this->Items) { ?>
          <?php foreach($this->Items as $key => $val){
          	
				$selected = $this->formCheckbox('selected[]', $val['product_id']);
								
				if($val['status'] == 1){	
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/product_id/' . $val['product_id']);											
					$status = $this->cmsIconButton('Active', HTTP_IMAGES. '/icon/icon_16_active.png', $linkStatus);
				}else{
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/product_id/' . $val['product_id']);
					$status = $this->cmsIconButton('INactive', HTTP_IMAGES. '/icon/icon_16_inactive.png', $linkStatus);
				}
										
				$linkInfo = $this->baseUrl($this->currentController . '/info/product_id/' . $val['product_id']);											
				$btnInfo = $this->cmsIconButton('View Item', HTTP_IMAGES. '/icon/icon_16_info.png', $linkInfo);
				$linkEdit = $this->baseUrl($this->currentController . '/edit/product_id/' . $val['product_id']);
				$btnEdit = $this->cmsIconButton('Edit Item', HTTP_IMAGES. '/icon/icon_16_edit.png', $linkEdit);
				$linkDelete	= $this->baseUrl($this->currentController . '/delete/product_id/' . $val['product_id']);
				$btnDelete = $this->cmsIconButton('Delete Item', HTTP_IMAGES. '/icon/icon_16_del.png', $linkDelete);
				$strIconButton = $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
		  ?>
          <tr>            
            <td align="center"><?php echo $selected;?></td>
            <td align="left"><?php echo $val['product_id'];?></td>
            <td align="left"><?php echo $val['name'];?></td>
            <td align="center"><?php echo $status;?></td>
            <td align="center"><?php echo $val['sort_order'];?></td>
            <td align="center"><?php echo date('d/m/Y', strtotime($val['date_added']));?></td>
 			<td align="right"><?php echo $strIconButton;?></td>
          </tr>
          <?php } ?>
          <?php } else { ?>
          <tr>
            <td class="center" colspan="7">Không có kết quả nào!</td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
    </form>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
</div>
</div>