<div id="content">
<?php echo $this->flashMessenger(); ?>
<div class="toolbox">
	<div class="left"><?php echo $this->cmsTranslator('config_server_page_title'); ?></div>
	<?php		
		//1. Save - submit
		$btnSave = $this->cmsButton(
						$this->cmsTranslator('config_server_save_button'),
						$this->baseUrl($this->currentController . '/mail'),
						HTTP_IMAGES . '/icon/icon-32-save.png',
						'submit'
					);
										
		//2. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right"><?php echo $btnSave;?><?php echo $btnCancel;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo HTTP_SERVER . '/admin/config/app/';?>">Hệ thống</a>
	<a href="<?php echo HTTP_SERVER . '/admin/user/index/';?>">Member Manager</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form" style="margin-bottom:0;">
        <tr>
          <td><?php echo $this->cmsTranslator('config_mail_protocol'); ?></td>
          <td><select name="protocol" id="protocol" style="width: 200px">
				<option value="smtp"<?php if ($this->protocol == 'smtp') : ?> selected="selected"<?php endif; ?>><?php echo $this->cmsTranslator('config_use_smtp'); ?></option>
			</select></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('config_smtp_host'); ?></td>
          <td><input type="text" name="host" style="width: 200px"<?php if ($this->host != null) : ?> value="<?php echo $this->host; ?>"<?php endif; ?> /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('config_smtp_port'); ?></td>
          <td><input type="text" name="port" style="width: 50px"<?php if ($this->port != null) : ?> value="<?php echo $this->port; ?>"<?php endif; ?> /></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><input type="checkbox" name="authentication" id="authentication" value="true"<?php if ($this->username != null) : ?> checked="checked"<?php endif; ?> /> <?php echo $this->cmsTranslator('config_smtp_authentication'); ?></td>
        </tr>
      </table>				
      <table class="form" id="authenticationContainer" style="display: <?php if ($this->username == null) : ?>none<?php else : ?>block<?php endif; ?>; margin-bottom:0;">
        <tr>
          <td><?php echo $this->cmsTranslator('config_smtp_username'); ?></td>
          <td><input type="text" name="username" style="width: 200px"<?php if ($this->username != null) : ?> value="<?php echo $this->username; ?>"<?php endif; ?> /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('config_smtp_password'); ?></td>
          <td><input type="password" name="password" style="width: 200px"<?php if ($this->password != null) : ?> value="<?php echo $this->password; ?>"<?php endif; ?> /></td>
        </tr>
      </table>
      <table class="form">
        <tr>
          <td><?php echo $this->cmsTranslator('config_smtp_security'); ?></td>
          <td><select name="security">
					<option value=""<?php if ($this->security == null) : ?> selected="selected"<?php endif; ?>><?php echo $this->cmsTranslator('config_smtp_not_security'); ?></option>
					<option value="tls"<?php if ($this->security == 'tls') : ?> selected="selected"<?php endif; ?>><?php echo $this->cmsTranslator('config_smtp_tls'); ?></option>
					<option value="ssl"<?php if ($this->security == 'ssl') : ?> selected="selected"<?php endif; ?>><?php echo $this->cmsTranslator('config_smtp_ssl'); ?></option>
				</select></td>
        </tr>
      </table>
    </form>
    <script type="text/javascript">
	$(document).ready(function() {	
		$('#authentication').click(function() {
			if ($(this).is(':checked')) {
				$('#authenticationContainer').show();
			} else {
				$('#authenticationContainer').hide();
			}
		});
	});
	</script>
</div>
</div>
