<?php echo $this->doctype();?>
<html>
	<head>
		<?php echo $this->headTitle();?>
		<?php echo $this->headMeta();?>
		<?php echo $this->headLink();?>
		<?php echo $this->headStyle();?>
		<?php echo $this->headScript();?>
		<link id="layout" href="<?php echo HTTP_PUBLIC."/skins/front/layout/3A.css";?>" rel="stylesheet" type="text/css">
	</head>
	<?php session_start(); 
		$_SESSION["back"] = $_SERVER['REQUEST_URI'];
	?>
	<body>
		<div id="container">
			<?php echo $this->render('_partial/_toolbar.phtml');?>
			<div id="web-body">
				<?php echo $this->render('_partial/_header.phtml');?>
				<?php echo $this->blkFrontMenu2();?>
				<div id="col-1" class="changeable">
					<?php echo $this->render('_partial/_left.phtml');?>
				</div>
				<div id="col-main" class="changeable">
					<?php echo $this->render('_partial/_main.phtml');?>
				</div>
				<div id="col-2" class="changeable">
					<?php echo $this->render('_partial/_right.phtml');?>
				</div>
				<div class="clear"></div>
			</div>
			<?php echo $this->render('_partial/_footer.phtml');?>
		</div>
	</body>
</html>