<?php echo $this->doctype();?>
<html>
<head>
<?php echo $this->headTitle();?>
<?php echo $this->headMeta();?>
<?php echo $this->headLink();?>
<?php echo $this->headStyle();?>
<?php echo $this->headScript();?>
</head>
<body>
<div id="container">
<?php echo $this->render('_partial/_header.phtml');?>
	<?php echo $this->layout()->content ?>
<?php echo $this->render('_partial/_footer.phtml');?>
</div><!-- End #container -->
</body>
</html>