<div id="container">
<div id="header">
  <div class="div1">
    <div class="div2"><img src="<?php echo HTTP_PUBLIC ;?>/skins/admin/images/logo.png" title="Trang Quản Trị" onclick="location = '#'" /></div>
      </div>
  </div>
<div id="content">
  <div class="login" style="width: 400px; min-height: 300px; margin-top: 40px; margin-left: auto; margin-right: auto;">
    <div class="heading">
      <h1><img src="<?php echo HTTP_PUBLIC ;?>/skins/admin/images/lockscreen.png" alt="" /> <?php echo $this->cmsTranslator('auth_login_page_title'); ?></h1>
    </div>
    <div class="content" style="min-height: 150px; overflow: hidden;">
      <?php if($this->messageError) { ?>
      <div class="warning"><?php echo $this->cmsTranslator('auth_login_failure'); ?></div>
      <?php } ?>
      <form action="/Zend/admin/auth/login" method="POST" enctype="multipart/form-data"  id="loginForm">
        <table style="width: 100%;">
          <tr>
            <td style="text-align: center;" rowspan="4"><img src="<?php echo HTTP_PUBLIC ;?>/skins/admin/images/login.png" alt="<?php echo $this->cmsTranslator('auth_login_user_name_required'); ?>" /></td>
          </tr>
          <tr>
            <td><?php echo $this->cmsTranslator('auth_login_user_name'); ?><br />
              <input type="text" name="username" value="" style="margin-top:3px;" />
              <span style="display: block; margin-top: 4px;"><?php echo $this->cmsTranslator('auth_login_password'); ?></span>
              <input type="password" name="password" value="" style="margin-top:3px;" />
              <a style="display: block; margin-top: 4px;" href="#"><?php echo $this->cmsTranslator('auth_forgot_password'); ?></a></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td style="text-align: right;"><a onclick="$('#loginForm').submit();" class="button"><span><?php echo $this->cmsTranslator('auth_login_submit_button'); ?></span></a></td>
          </tr>
        </table>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#loginForm').validate({
		rules: {
			username: {
		  		required: true
			},
			password: {
				required: true
			}
	    },
	    messages: {
	    	username: {
	        	required: "<?php echo $this->cmsTranslator('auth_login_user_name_required'); ?>"
			},
			password: {
	        	required: "<?php echo $this->cmsTranslator('auth_login_password_required'); ?>"
			}
		}
	});
});
</script>
</div>
<div id="footer">Hỗ trợ bởi <a href="#">huydang1920@gmail.com</a> &copy; 2009-2011</div>