<?php
$this->headTitle($this->translator('auth_reset_page_title'));
?>

<div class="grid_8 prefix_2 suffix_2">
	<h1>TomatoCMS</h1>
	
	<div class="alpha grid_4 prefix_2">
		<?php if ($this->invalidLink) : ?>
		<div class="t_a_message_warning"><?php echo $this->translator('auth_reset_invalid_link'); ?></div>
		<?php else : ?>
		<div class="t_a_message"><?php echo $this->translator('auth_reset_sent_mail'); ?></div>
		<?php endif; ?>
	</div>
</div>
