<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->headScript() ?>
</head>
<body>
<div id="wrapper">

<?php echo $this->render('_partial/_header.phtml');?>

<div id="main-menu">
	<ul>
		<li><a href="<?php echo $this->baseUrl("/admin")?>">Site</a></li>
		<li><a href=#>Menu</a></li>
		<li><a href=#>Content</a></li>
		<li><a href=#>Component</a></li>
		<li><a href=#>Extensions</a></li>
		<li><a href=#>Tools</a></li>
		<li><a href=#>Help</a></li>
	</ul>	
</div>

<div id="content">	
	<?php echo $this->layout()->content ?>
</div><!-- end #content -->

<?php echo $this->render('_partial/_footer.phtml');?>

</div><!-- end #wrapper -->
</body>	
</html>
	
