<div style="text-align: left">
	
</div>
<h2>Bạn có muốn xóa Bài đăng này không?</h2>
<p>Title: <?php echo $this->news_item['title'] ?></p>
<p>Author:<?php echo $this->news_item['author']?></p>
<p><?php ?></p>
<p><?php ?></p>
<form>
<input id="Checkbox_yes" type="checkbox">Yes
<a href="<?php echo $this->baseUrl("/admin/news/delete")?>">Delete</a>
</form>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><