<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php
		//1. Add new - link
		$btnAddNew = $this->cmsButton(
						'Add new',
						$this->baseUrl($this->currentController . '/add'),
						HTTP_IMAGES . '/icon/icon-32-new.png',
						'link'
					);
		//2. Active - submit
		$btnActive = $this->cmsButton(
						'Active Items',
						$this->baseUrl($this->currentController . '/status/type/1'),											
						HTTP_IMAGES . '/icon/icon-32-active.png',
						'submit'
					);
		//3. Inactive- submit
		$btnInactive = $this->cmsButton(
						'Inactive Items',
						$this->baseUrl($this->currentController . '/status/type/0'),										
						HTTP_IMAGES . '/icon/icon-32-inactive.png',
						'submit'
					);

		//4. Delete - submit
		$btnDelete = $this->cmsButton(
						'Delete Items',
						$this->baseUrl($this->currentController . '/multi-delete'),
						HTTP_IMAGES . '/icon/icon-32-delete.png',
						'submit'
					);	
		
	?>
	<div class="right"><?php echo $btnAddNew;?><?php echo $btnActive;?><?php echo $btnInactive;?><?php echo $btnDelete;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo HTTP_SERVER . '/admin/userpermission/index/';?>">Group Manager</a>
	<a href="<?php echo HTTP_SERVER . '/admin/user/index/';?>">Member Manager</a>
</div>
<div class="content">
	<?php	
		$filter = $this->arrParam['filter'];
		$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
		
		$sortID 		= $this->cmsLinkSort('ID','u.user_id', $filter, $action_link);
		
		$sortUsername 	= $this->cmsLinkSort('Username','u.username', $filter, $action_link);
		
		$sortStatus		= $this->cmsLinkSort('Status','u.status', $filter, $action_link);
											
		$sortEmail		= $this->cmsLinkSort('Email','u.email', $filter, $action_link);			
	
		$sortDateAdded	= $this->cmsLinkSort('Registed','u.date_added', $filter, $action_link);
											
		$sortGroup 		= $this->cmsLinkSort('Group','group', $filter, $action_link);
		
		//-------------------CREATE GROUP SELECTBOX ------------------------
		$linkSlbGroup = $this->baseUrl($this->currentController . '/filter/type/group');
		$options = $this->group;
		$selectGroup = $this->formSelect('user_group_id', $filter['user_group_id'],
										array('onchange'=>"OnSubmitForm('" . $linkSlbGroup . "')"),
										$options);
																
	?>
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
      <table class="list">
        <thead>
          <tr>
            <td width="1" style="text-align: center;">
            	<input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" />
            </td>            
            <td class="left"><?php echo $sortID;?></td>
            <td class="left"><?php echo $sortUsername;?></td>
            <td class="center"><?php echo $sortStatus;?></td>
            <td class="center"><?php echo $sortEmail;?></td>
            <td class="center"><?php echo $sortDateAdded;?></td>
            <td class="center"><?php echo $sortGroup;?></td>
            <td class="right">Control</td>
          </tr>
        </thead>
        <tbody>
          <tr class="filter">
            <td></td>
            <td></td>
            <td><input type="text" name="filter_username" value=""/></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="center"><?php echo $selectGroup;?></td>
            <td class="right">
            	<a class="button" onclick="OnSubmitForm('<?php echo $this->baseUrl($this->currentController . '/filter/type/search/key/1'); ?>')"><span>filter</span></a>
            	<a class="button" onclick="OnSubmitForm('<?php echo $this->baseUrl($this->currentController . '/filter/type/search/key/0'); ?>')"><span>clear</span></a>
            </td>
          </tr>
          <?php if ($this->Items) { ?>
          <?php foreach($this->Items as $key => $val){
          	
				$selected = $this->formCheckbox('selected[]', $val['user_id']);
								
				if($val['status'] == 1){	
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/user_id/' . $val['user_id']);											
					$status = $this->cmsIconButton('Active', HTTP_IMAGES. '/icon/icon_16_active.png', $linkStatus);
				}else{
					$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/user_id/' . $val['user_id']);
					$status = $this->cmsIconButton('INactive', HTTP_IMAGES. '/icon/icon_16_inactive.png', $linkStatus);
				}
										
				$linkInfo = $this->baseUrl($this->currentController . '/info/user_id/' . $val['user_id']);											
				$btnInfo = $this->cmsIconButton('View Item', HTTP_IMAGES. '/icon/icon_16_info.png', $linkInfo);
				$linkEdit = $this->baseUrl($this->currentController . '/edit/user_id/' . $val['user_id']);
				$btnEdit = $this->cmsIconButton('Edit Item', HTTP_IMAGES. '/icon/icon_16_edit.png', $linkEdit);
				$linkDelete	= $this->baseUrl($this->currentController . '/delete/user_id/' . $val['user_id']);
				$btnDelete = $this->cmsIconButton('Delete Item', HTTP_IMAGES. '/icon/icon_16_del.png', $linkDelete);
				$strIconButton = $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
		  ?>
          <tr>            
            <td align="center"><?php echo $selected;?></td>
            <td align="left"><?php echo $val['user_id'];?></td>
            <td align="left"><?php echo $val['username'];?></td>
            <td align="center"><?php echo $status;?></td>
            <td align="center"><?php echo $val['email'];?></td>
            <td align="center"><?php echo date('d/m/Y H:i:s', strtotime($val['date_added']));?></td>
            <td align="center"><?php echo $val['group'];?></td>
 			<td align="right"><?php echo $strIconButton;?></td>
          </tr>
          <?php } ?>
          <?php } else { ?>
          <tr>
            <td class="center" colspan="8">Không Có Kết Quả Phù Hợp</td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
    </form>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/manager');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
</div>
</div>