<?php
$layoutConfig = new Zend_Config_Ini(APPLICATION_PATH.DS."configs/application.ini", "layout"); 
?>
<script>
var currentLayout="<?php echo $layoutConfig->currentLayout;?>";
function showMessage(message) {
	$("#message-content").html(message);
	$("#message").dialog("open");
};

function closeMessage() {
	$("#message").dialog("close");
};

$(function(){
	//Init message dialog
	$("#message").dialog({
		autoOpen: false,
		height: 100,
		width: 200,
		modal: true
	});

	//Init choose-layout-form dialog
	$("#choose-layout-form").dialog({
		autoOpen: false,
		height: 400,
		width: 700,
		modal: true,
		buttons: {
			"Save": function(){
				currentLayout = $("input[name=rdoLayout]:checked").val();
				$.ajax({
					
					type: 'POST',
					url: '<?php echo HTTP_SERVER."front/index/savelayout"?>',
					dataType: 'json',
					data: {
						currentLayout: currentLayout
					},
					success: function(data) {
						closeMessage();	
					},
					error: function(request, error) {
						showMessage("Error! <br> Detail: <br>" + request.responseText);
					}	
				});
				$("#layout").attr("href", "<?php echo HTTP_PUBLIC."/skins/front/layout/"?>" + currentLayout + ".css");
				$(this).dialog("close");
			},
			Cancel: function(){
				$(this).dialog("close");
			}
		}
	});

	//Init toolbar buttons
	$("#btnMoreModules").button().click(function(){
		
	});

	$("#btnSelectLayout").button().click(function(){
		$("#choose-layout-form").dialog("open");
		for(i = 0; i < $("input[name=rdoLayout]").length; i++) {
			if ($("input[name=rdoLayout]")[i].value == currentLayout) {
				$("input[name=rdoLayout]")[i].checked = true;
			} else {
				$("input[name=rdoLayout]")[i].checked = false;
			}
		}
	});
	
	$("#chkLayoutModules").button().click(function(){
		if($(this).is(":checked")) {
			//Turn on Layout Mode
			$(this).button({
				label: "Layout Mode: ON"
				});
			$(".state-changable-button").button("option", "disabled", true);
			$("#col-1, #col-2, #col-main").sortable("enable");
		} else {
			//Turn off Layout Mode
			$(this).button({
				label: "Layout Mode: OFF"
				});
			$(".state-changable-button").button("option", "disabled", false);
			$("#col-1, #col-2, #col-main").sortable("disable");
		}
	});

	//Layout followed setting
	$("#layout").attr("href", "<?php echo HTTP_PUBLIC."/skins/front/layout/"?>" + currentLayout + ".css");

	//Allow sort modules but disable until turn on Layout Mode
	$("#col-1, #col-2, #col-main").sortable({
		connectWith: ".changeable",
		cancel: "#main-content"
	});
	$("#col-1, #col-2, #col-main").disableSelection();
	$("#col-1, #col-2, #col-main").sortable("disable");
});
</script>

<!-- Define MessageBox with default information -->
<div id="message">
	<p id="message-content" align="center">Saving...</p>
</div>

<!-- Toolbar for administrator's editor mode -->
<div id="admin-toolbar" class="ui-widget-header ui-corner-all">
	<div id="btnMoreModules" class="state-changable-button">More Modules</div>
	<div id="btnSelectLayout" class="state-changable-button">Select Layout</div>
	<input type="checkbox" id="chkLayoutModules"/>
	<label for="chkLayoutModules">Layout Mode: OFF</label>
</div>

<div id="choose-layout-form" title="Select Page Layout">
	<input type="radio" name="rdoLayout" value="3A">
	<img src="<?php echo HTTP_IMAGES.DS."layout".DS."3A.JPG";?>">
	<input type="radio" name="rdoLayout" value="3B">
	<img src="<?php echo HTTP_IMAGES.DS."layout".DS."3B.JPG";?>">
	<input type="radio" name="rdoLayout" value="3C">
	<img src="<?php echo HTTP_IMAGES.DS."layout".DS."3C.JPG";?>"><br>
	<input type="radio" name="rdoLayout" value="2A">
	<img src="<?php echo HTTP_IMAGES.DS."layout".DS."2A.JPG";?>">
	<input type="radio" name="rdoLayout" value="2B">
	<img src="<?php echo HTTP_IMAGES.DS."layout".DS."2B.JPG";?>">
</div>