<table class="list" style="margin-bottom: 0px;">
			<thead>
				<tr>
					<td class="left" style="min-width: 100px">Product Name</td>
					<td class="center">Price <br><span style="font-size:6pt">(Thousand vnd)</span></td>					
				</tr>
			</thead>
			<tbody>
				<?php if ($this->items) { ?>
				<?php foreach($this->items as $val){
										
					?>
					<tr>
						
						<td><a href="<?php echo HTTP_SERVER.'/front/product/detail/product_id/'.$val['product_id'].'#main-content'?>"><?php echo $val["model"]?></a></td>
		            	<td class="center"><?php echo $val["price"]/1000?></td>		            	
            		</tr>
	          	<?php } ?>
          		<?php } else { ?>
			        <tr>
			            <td class="center" colspan="2">Không có k?t qu?</td>
			        </tr>
          		<?php } ?>
			</tbody>
		</table>