<div id="content">
  <div class="breadcrumb"></div>
  <?php if ($this->Items) { ?>
  <div class="product-grid"> 
    <?php foreach ($this->Items as $product) { ?>
    <div>
      <?php if ($product['image']) { ?>
      <div class="image"><a class="fancybox" href="<?php echo $this->baseUrl($this->currentController . '/detail/product_id/' . $product['product_id']);?>" title="<?php echo $product['name']; ?>"><img src="<?php echo HTTP_IMAGES . '/' . $product['image']; ?>" alt="<?php echo $product['model']; ?>" width="90" height="90" title="<?php echo $product['name']; ?>" /></a></div>
      <?php } ?>
      <div class="name"><a href="<?php echo $this->baseUrl($this->currentController . '/detail/product_id/' . $product['product_id']);?>"><?php echo $product['name']; ?></a></div>
      <div class="description"><?php //echo html_entity_decode($product['description'], ENT_QUOTES, 'UTF-8'); ?></div>
      <?php if ($product['price']) { ?>
      <div class="price">
        <?php echo round($product['price']) . 'đ'; ?>
      </div>
      <?php } ?>
      <div class="cart" style="display: none;"><a onclick="addToCart('');" class="button"><span>Giỏ hàng</span></a></div>
    </div>
    <?php } ?>
  </div>
  <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
  </div>
  <?php } ?>
</div>