<div id="content">
	<div class="toolbox">
		<div class="left">Qu?n l? :: Tin T?c - S? Ki?n</div>
		<div class="right">
			<div><a href="<?php echo $this->baseUrl("/admin/news/new")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>"/><br>New</a></div>
			<div><a href="<?php echo $this->baseUrl("/admin/news/edit")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>"/><br>Edit</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active</a></div>
		</div>
	</div>
	<div class="breadcrumb">
		<a href="#">...</a>
		<a href="#">...</a>
	</div>
	<table border="1" cellpadding="1" cellspacing="0">
	<tr style="font-weight: bold;"> <td>ID</td> <td>TIÊU Ð?</td> <td>TÁC GI?</td> <td>H?NH ?NH</td> <td>LÝ?T XEM</td> <td>TH? T?</td> <td>TR?NG THÁI</td> <td>NGÀY T?O</td> <td>NGÀY S?A</td> <td>THAO TÁC</td></tr> 
	<?php 
	foreach($this->news as $news){
		$news_description = $this->model->getNews_description($news['news_id'],"vi_VN");
		echo '<tr><td>'.$news["news_id"];
		echo '</td> <td>'.$news_description['title'];
		echo '</td> <td>'.$news['author'];
		echo "</td> <td>".$news["image"];
		echo '</td> <td>'.$news['viewed'];
		echo '</td> <td>'.$news['sort_order'];
		echo '</td> <td>'.$news['status'];
		echo '</td> <td>'.$news["date_added"];
		echo '</td> <td>'.$news["date_modified"];
		echo '</td><td><a href='.$this->baseUrl("/admin/news/edit")."?news_id=".$news['news_id'].'>S?a</a>  &nbsp&nbsp  <a href='.$this->baseUrl("admin/news/delete")."?news_id=".$news['news_id'].'>Xóa</a> &nbsp&nbsp <a>Active</a></td></tr>';
	}
	?>

	</table>
	<pre>
		<?php print_r($this->news);?>
	</pre>
	
</div>


