<div id="content">
  <div class="breadcrumb"></div>
  <?php if ($this->products) { ?>
  <div class="product-grid">
    <?php foreach ($this->products as $product) { ?>
    <div>
      <?php if ($product['image']) { ?>
      <div class="image"><a class="fancybox" href="#" title="<?php echo $product['name']; ?>"><img src="<?php echo HTTP_IMAGES . '/' . $product['image']; ?>" alt="<?php echo $product['model']; ?>" width="90" height="90" title="<?php echo $product['name']; ?>" /></a></div>
      <?php } ?>
      <div class="name"><a href="#"><?php echo $product['name']; ?></a></div>
      <div class="description"><?php //echo html_entity_decode($product['description'], ENT_QUOTES, 'UTF-8'); ?></div>
      <?php if ($product['price']) { ?>
      <div class="price">
        <?php echo $product['price']; ?>
      </div>
      <?php } ?>
      <div class="cart"><a onclick="addToCart('');" class="button"><span>Giỏ hàng</span></a></div>
    </div>
    <?php } ?>
  </div>
  <?php } ?>
</div>