<div id="gallery">
<?php 
      function recursiveDelete($directory,$folder) {
		$handle = null;
		if (is_dir($directory)) {
			//echo "directory not correct";
			$handle = opendir($directory);
		}
		
		if (!$handle) {
			return false;
		}
		$dem=0;
		while (false !== ($file = readdir($handle))) {
			if($dem==4){
				$dem=0;
				echo '</ul>';
			}
			if ($file != '.' && $file != '..' ) {
				if(substr($file, -4)==".JPG" || substr($file, -4)==".PNG"
				|| substr($file, -4)==".jpg" || substr($file, -4)==".png"){
				$dem++;
				if($dem==0){
					echo '</ul>';
				}else{ 
					if($dem==1) echo '<ul>';
				}
				if (!is_dir($directory . '/' . $file)) {
					$nameImage=$file;
					if($folder!="") $nameImage=$folder.'/'.$file;
					
					echo '<li><a href = "'. HTTP_IMAGES.'/data/hinhanh/'.$nameImage . '">';
					echo '<img src = "'. HTTP_IMAGES.'/data/hinhanh/'.$nameImage.'" width="100" height="100"/></a><li>';
				} else {
					//$this->recursiveDelete($directory . '/' . $file);
				}
			}
			}
			
		}
		if($dem==4) echo '</ul>';
		closedir($handle);
	}
	//echo recursiveDelete(getcwd ().'\public\images\data\hinhanh');
	//echo showfolder(getcwd ().'\public\images\data\hinhanh');
	function showfolder($directory,$chon) {
		$handle = null;
		if (is_dir($directory)) {
			//echo "directory not correct";
			$handle = opendir($directory);
		}
		
		if (!$handle) {
			return false;
		}
		$dem=0;
		while (false !== ($file = readdir($handle))) {
		
			if (1) {
				if (substr($file, -4)!=".JPG" && $file!=".." && substr($file, -4)!=".png"
				&& substr($file, -4)!=".PNG" && substr($file, -4)!=".gif" && $file!="." && substr($file, -4)!=".jpg") {
					if($file==$chon)
						echo "<option selected='selected' value='$file'>$file</option>\n";
					else echo "<option value='$file'>$file</option>\n";
				} else {
				//	$this->showfolder($directory . '/' . $file);
				}
			}
			
		}
		
		closedir($handle);
	}
	
	
	
?>

<form class="naviform" action="" name="tftnavi" method="post">
	<select name="album" onchange="javascript:document.tftnavi.submit();">
	<option value='empty' >Chọn thư mục</option> 
	<?php
		echo showfolder(getcwd ().'\public\images\data\hinhanh',$this->huy); 
	?>
	</select>
	
</form>

<?php 
	if($this->huy!="") {
		//echo recursiveDelete(getcwd ().'\public\images\data\hinhanh\Congty');
		$baodinh='\public\images\data\hinhanh\\'.$this->huy;
		echo recursiveDelete(getcwd ().$baodinh,$this->huy);
	}
	else echo recursiveDelete(getcwd ().'\public\images\data\hinhanh',$this->huy);
?>
</div>

<!-- Arquivos utilizados pelo jQuery lightBox plugin -->
  
    <script type="text/javascript" src="<?php echo HTTP_JAVASCRIPT?>/js/jquery.lightbox-0.5.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo HTTP_JAVASCRIPT?>/css/jquery.lightbox-0.5.css" media="screen" />
    <!-- / fim dos arquivos utilizados pelo jQuery lightBox plugin -->
    
    <!-- Ativando o jQuery lightBox plugin -->
    <script type="text/javascript">
    $(function() {
        $('#gallery a').lightBox();
    });
    </script>
   	<style type="text/css">
	/* jQuery lightBox plugin - Gallery style */
	#gallery {
		background-color: #444;
		padding: 10px;
		width: 520px;
	}
	#gallery ul { list-style: none; }
	#gallery ul li { display: inline; }
	#gallery ul img {
		border: 5px solid #3e3e3e;
		border-width: 5px 5px 20px;
	}
	#gallery ul a:hover img {
		border: 5px solid #fff;
		border-width: 5px 5px 20px;
		color: #fff;
	}
	#gallery ul a:hover { color: #fff; }
	</style>