<?php
//Get options from database
$modules = new Front_Model_Module();
$header = $modules->getItemByName("Header");

//set default values;
$banner = "header_1.jpg";
$title = "C&C1";
$welcome_text = "Bring you the easiest way to own Websites.";

if($header!=null) {
	//if header's information exists in db, load option
	eval($header['option']);
} else {
	$header = array("name" => "Header", "module_id" => "", "file_name" => "");
}
?>
<script>
var imageRoot = "<?php echo HTTP_IMAGES;?>";
var imageLink = "<?php echo $banner;?>";
var pageTitle = "<?php echo $title;?>";
var welcomeText = "<?php echo $welcome_text;?>";

$(function() {
	function updateHeader() {
		$("#banner").attr("src", imageLink);
		$("#page-title").html(pageTitle);
		$("#welcome-text").html(welcomeText);
		var option_str = "$banner='" + imageLink + "';$title='" + pageTitle + "';$welcome_text='" + welcomeText +"';"

		$.ajax({
			type: 'POST',
			url: '<?php echo HTTP_SERVER."front/index/saveblock"?>',
			dataType: 'json',
			data: {
				module_id: "<?php echo $header['module_id'];?>",
				name: "<?php echo $header['name'];?>",
				file_name: "<?php echo $header['file_name'];?>",
				is_showed: 1,
				position: 0,
				sort_order: 0,
				option: option_str
			},
			success: function(data) {
				closeMessage();	
			},
			error: function(request, error) {
				showMessage("Error! <br> Detail: <br>" + request.responseText);
			}	
		});
	}
	
	$("#banner").attr("src", imageLink);
	$("#page-title").html(pageTitle);
	$("#welcome-text").html(welcomeText);
	$("#choose-image-form").dialog({
		autoOpen: false,
		height: 600,
		width: 600,
		modal: true,
		buttons: {
			"Save": function() {
				var str = $("input[name='rdoBannerImage']:checked").val();
				$("#txtUrl").val(str);
				$(this).dialog("close");
			},
			Cancel: function() {
				$(this).dialog("close");
			}
		}
	});
	$("#edit-header-form").dialog({
		autoOpen: false,
		height: 300,
		width: 350,
		modal: true,
		buttons: {
			"Save": function() {
				imageLink = $("#txtUrl").val();
				pageTitle = $("#txtTitle").val();
				welcomeText = $("#txtWelcomeText").val();

				showMessage("Saving...")
				updateHeader();
				$(this).dialog("close");
			},
			Cancel: function() {
				$( this ).dialog( "close" );
			}
		}
	});
	
	$('#edit-header').button().click(function() {
		$('[name=txtUrl]').val(imageLink);
		$("#txtTitle").val(pageTitle);
		$("#txtWelcomeText").val(welcomeText);
		$("#edit-header-form").dialog( "open" );
	})

	function image_upload(field, thumb) {
		$('#dialog').remove();
		$strlayout = '<div id="dialog" style="padding: 3px 0px 0px 0px;"> <div id = "11111"><iframe id = "123" src="' + "<?php echo HTTP_SERVER?>" + 'admin/filemanager?field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div></div>';
		$('#content').prepend($strlayout);
		
		$('#dialog').dialog({
			
			title: 'Quản lý hình ảnh',
			close: function (event, ui) {
				//alert("event clicked");
				if ($('#' + field).attr('value')) {
					$.ajax({
						url: "<?php echo HTTP_SERVER;?>" + 'admin/filemanager/image?image=' + encodeURIComponent($('#' + field).val()),
						dataType: 'text',
						success: function(data) {
							//$('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
						}
					});
				}
				var imglink = "<?php echo HTTP_SERVER;?>" + "public/images/" + $("#txtUrl").val();
				$("#txtUrl").val(imglink);
				//alert($("#txtUrl").val());
				$("#txtUrl").change();
			},	
			bgiframe: false,
			width: 800,
			height: 400,
			resizable: false,
			modal: true
		});
	};
	
	$("#choose-image").button().click(function(){
		/*$("input[name='rdoBannerImage']").each(function(){
			if($(this).val() == imageLink) {
				$(this).prop('checked', true);
			} else {
				$(this).prop('checked', false);
			}
		});
		$("#choose-image-form").dialog("open");
		*/
		image_upload('txtUrl', 'thumb');
	});
});
</script>
<div id="header">
	<img id="banner" style="width: 100%"/>
	<div class='edit-button'>
		<button id='edit-header' class="state-changable-button">...</button>
	</div>
	<div id="page-title"></div>
	<div id="welcome-text"></div>
	
	<div id="edit-header-form" title="Edit Page Header.">
		<form style="position: relative;">
		<table border="0px;" width="100%">
			<tr>
				<td width="100px;"><label for="txtUrl">Banner URL</label></td>
				<td><input type="text" name="txtUrl" id="txtUrl" maxlength="200" size="30"/>
				<div id="choose-image">...</div></td>
			</tr>
			<tr>
				<td width="100px;"><label for="txtTitle">Page Title</label></td>
				<td><input type="text" name="txtTitle" id="txtTitle" maxlength="50" size="40"/></td>
			</tr>
			<tr>
				<td width="100px;"><label for="txtWelcomeText">Welcome Text</label></td>
				<td><input type="text" name="txtWelcomeText" id="txtWelcomeText" maxlength="200" size="40"/></td>
			</tr>
		</table>
	    </form>
	</div>
	
	<div id="choose-image-form">
		Notice: This form will be replaced by Media Manager (TuanVA)<br>
		<input type="radio" name="rdoBannerImage" value="header_1.jpg">
		<img alt="" src= "<?php echo HTTP_IMAGES.DS."header_1.jpg"?>" style="width:500px; height:150px"><br>
		<input type="radio" name="rdoBannerImage" value="header_2.jpg">
		<img alt="" src= "<?php echo HTTP_IMAGES.DS."header_2.jpg"?>" style="width:500px; height:150px"><br>
	</div>
	
</div>