<?php
$modules = new Front_Model_Module();
$moduleList = $modules->listItem(COL_MAIN_POSITION);
foreach($moduleList as $module) {
	if($module['name'] == "Main") {
?>
		<div id="main-content" class="ui-widget-content ui-conner-all module">
			<script>
			function loadSiteList() {
				$("#site-manager-form-content").html("Loading...");
				$.ajax({
					type: 'POST',
					url: '<?php echo HTTP_SERVER."front/sites/index"?>',
					success: function(data) {
						$("#site-manager-form-content").html(data);
					},
					error: function(request, textStatus, error) {
						showMessage("Error! <br> Detail: <br>" + request.responseText + error);
					}	
				});
			}
			
			$(function() {
				$("#site-manager-form").dialog({
					autoOpen: false,
					width: 400,
					height: 500,
					modal: true,
					buttons: {
						"New Site": function() {
							$("#edit-site-form").dialog("open");
							$("#edit-site-form-content").html("Loading...");
							$.ajax({
								type: 'POST',
								url: '<?php echo HTTP_SERVER."front/sites/new"?>',
								success: function(data) {
									$("#edit-site-form-content").html(data);
								},
								error: function(request, textStatus, error) {
									showMessage("Error! <br> Detail: <br>" + request.responseText + error);
								}	
							});
						},
						"Close": function() {
							$(this).dialog("close");
						}
					}
				});
				
				$("#edit-site-form").dialog({
					autoOpen: false,
					width: 800,
					height: 600,
					modal: true,
					buttons: {
						"OK": function() {
							saveSite();
						},
						"Close": function() {
							$(this).dialog("close");
						}
					}
				});
				
				$("#sites-manager").button().click(function() {
					$("#site-manager-form").dialog("open");
					loadSiteList();
				});
			});
			</script>
			<div class="module-title">
				<div class="edit-button">
					<button id='sites-manager' class="state-changable-button" style="z-index:1000;">...</button>
				</div>
			</div>
			
			<div id="site-manager-form" title="Sites Manager">
				<div id="site-manager-form-content">
				</div>
			</div>
			<div id="edit-site-form" title="Sites Manager">
				<div id="edit-site-form-content">
				</div>
			</div>
			<?php echo $this->layout()->content ?>
		</div>
<?php
	} else {
		$functionName = $module['file_name'];
		$info = $module;
		echo $this->$functionName($info);
	}
}