<div id="footer">
  <div class="column">
    <h3>Thông tin</h3>
    <ul>
      <li><a href="#">Thông tin</a></li>
    </ul>
  </div>
  <div class="column">
    <h3>Dịch vụ</h3>
    <ul>
      <li><a href="#">Dịch vụ</a></li>
    </ul>
  </div>
  <div class="column">
    <h3>Thông tin cá nhân</h3>
    <ul>
      <li><a href="#">Thông tin cá nhân</a></li>
    </ul>
  </div>
  <div class="column">
    <h3>Tài khoản</h3>
    <ul>
      <li><a href="#">Tài khoản</a></li>
    </ul>
  </div>
</div>
<div id="powered">Powered By huydang1920 copyright © 2011</div>
</div>
</body></html>