<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						$this->cmsTranslator('category_cancel_button'),
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br><?php echo $this->cmsTranslator('category_add_button');?></a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl($this->currentController . '/index');?>"><?php echo $this->cmsTranslator('category_home');?></a>
	<a href="#">??</a>
</div>
<div class="content">
	<form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
	<div id="languages" class="htabs">
	<?php foreach ($this->languages as $key => $value) { ?>
	<?php $language = explode('|', $value);?>
	<a href="#language_<?php echo $key; ?>">
		<img src="<?php echo HTTP_IMAGES . '/flags/' . $language[0] . '.png'; ?>" title="<?php echo $language[1]; ?>" />
		<?php echo $language[1]; ?>
	</a>
	<?php } ?>
	</div>
	<?php foreach ($this->languages as $language => $value) { ?>
	<div id="language_<?php echo $language; ?>">    
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('category_entry_name'); ?></td>
          <td><input type="text" name="category_description[<?php echo $language; ?>][name]" size="100" value="" /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_meta_keywords'); ?></td>
          <td><textarea name="category_description[<?php echo $language; ?>][meta_keyword]" cols="40" rows="5"></textarea></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_meta_description'); ?></td>
          <td><textarea name="category_description[<?php echo $language; ?>][meta_description]" cols="40" rows="5"></textarea></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_description'); ?></td>
          <td><textarea name="category_description[<?php echo $language; ?>][description]" id="description_<?php echo $language; ?>"></textarea></td>
        </tr>
      </table>
	</div>
	<?php } ?>
      <table class="form">
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_parent'); ?></td>
          <td><select name="parent_id">
                  <option value="0"><?php echo $this->cmsTranslator('category_text_select'); ?></option>
                  <?php foreach ($this->categories as $category) { ?>
                  <option value="<?php echo $category['category_id']; ?>"><?php echo $category['name']; ?></option>
                  <?php } ?>
                </select></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_top'); ?></td>
          <td><input name="top" type="checkbox" value="1" /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_column'); ?></td>
          <td><input type="text" name="column" value="" size="1" /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_image'); ?></td>
          <td><input type="text" name="image" onclick="openKCFinder(this)" readonly="readonly" value="" /></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('category_entry_sort_order'); ?></td>
          <td><input type="text" name="sort_order" value="" size="1" /></td>
        </tr>
		<tr>
		   <td><?php echo $this->cmsTranslator('category_entry_status'); ?></td>
           <td><select name="status">
                  <option value="1" selected="selected"><?php echo $this->cmsTranslator('category_text_enabled'); ?></option>
                  <option value="0"><?php echo $this->cmsTranslator('category_text_disabled'); ?></option>
                </select></td>
        </tr>
      </table>
    </form>
	<!-- khởi tạo editor -->
	<?php 
		$editor = array();
		foreach ($this->languages as $language => $value) {
			$editor[] = 'description_' . $language;
		}
		echo $this->cmsEditor($editor, array());
	?>	
	<!-- Ngày tháng -->
	<script type="text/javascript" src="<?php echo HTTP_PUBLIC . '/javascript/jquery/ui/jquery-ui-timepicker-addon.js';?>"></script> 
	<script type="text/javascript">
	$('.date').datepicker({dateFormat: 'yy-mm-dd'});
	$('.datetime').datetimepicker({
		dateFormat: 'yy-mm-dd',
		timeFormat: 'h:m'
	});
	$('.time').timepicker({timeFormat: 'h:m'});
	</script>
	<script type="text/javascript">
	function openKCFinder(field) {
	    window.KCFinder = {
	        callBack: function(url) {
	            window.KCFinder = null;
	            field.value = url;
	        }
	    };
	    window.open('<?php echo HTTP_PUBLIC;?>/scripts/kcfinder/browse.php?type=images&dir=images', 'kcfinder_textbox',
	        'status=0, toolbar=0, location=0, menubar=0, directories=0, ' +
	        'resizable=1, scrollbars=0, width=800, height=600'
	    );
	}
	</script>
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				<?php foreach ($this->languages as $language => $value) { ?>
					"category_description[<?php echo $language; ?>][name]": {
			  		required: true,
			  		minlength: 3,
			  		maxlength: 200,
			  	},
			  	<?php } ?>
		    },
		    messages: {		    	
		    	<?php foreach ($this->languages as $language => $value) { ?>
		    		"category_description[<?php echo $language; ?>][name]": {
		        	required: "<?php echo $this->cmsTranslator('user_user_name_required'); ?>",
					minlength: "<?php echo $this->cmsTranslator('user_user_name_minlength'); ?>",
					maxlength: "<?php echo $this->cmsTranslator('user_user_name_maxlength'); ?>",
				},
			  	<?php } ?>
			}
		});
	});
	</script>
	<script type="text/javascript">
		$('#languages a').tabs();
	</script> 
</div>
</div>