<div id="content">
	<div class="toolbox">
		<div class="left">Quản lý :: Tin Tức - Sự Kiện</div>
		<div class="right">
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>"/><br>New</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>"/><br>Edit</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active</a></div>			
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-delete.png';?>"/><br>Delete</a></div>
		</div>
	</div>
	<div class="breadcrumb">
		<a href="#">...</a>
		<a href="#">...</a>
	</div>
</div>