<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br>Lưu</a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo HTTP_SERVER . '/admin/userpermission/index/';?>">Group Manager</a>
	<a href="<?php echo HTTP_SERVER . '/admin/user/index/';?>">Member Manager</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td>Group Name:</td>
          <td><input type="text" name="name" value="<?php echo $this->Item['name'];?>" size="50" /></td>
        </tr>
        <tr>
          <td>Status: </td>
          <?php if($this->Item['status']) {?>
          <td>Active <input type="radio" name="status" value="1" checked="checked" />&nbsp;&nbsp;&nbsp;&nbsp;Inactive <input type="radio" name="status" value="0" /></td>
          <?php } else { ?>
          <td>Active <input type="radio" name="status" value="1"/>&nbsp;&nbsp;&nbsp;&nbsp;Inactive <input type="radio" name="status" value="0" checked="checked" /></td>
          <?php } ?>
        </tr>
        <tr>
           <td>Order</td>
           <td><input type="text" name="sort_order" value="<?php echo $this->Item['sort_order'];?>" size="1" /></td>
        </tr>
      </table>
    </form>
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				name: {
					required: true,
			  		minlength: 3,
				}
		    },
		    messages: {		    	
		    	name: {
		        	required: "Nhập tên nhóm",
		        	minlength:"Nhập tên nhóm",
				}
			}
		});
	});
	</script>
</div>
</div>