<?php
$menu = $this->item;

function showPosition($menu, $margin_left) {
	foreach($menu['children'] as $sub) {
		echo '<li class="ui-state-default" id="'.$sub['id'].'" style="margin-left:'.$margin_left.'px;">'.$sub['name']."</li>";
		showPosition($sub, $margin_left + 20);
	}
}
?>
<script>
var selected_id = 0;

function selectMenu () {
	$("child-sort").html("Loading...");
	$.ajax({
		type: 'POST',
		url: '<?php echo HTTP_SERVER."front/menu/childsort"?>',
		data: {
			parent_id: selected_id
		},
		success: function(data) {
			$("#child-sort").html(data);
		},
		error: function(request, status, error) {
			showMessage(error + "<br> Detail: <br>" + request.responseText);
		}	
	});
}

$(function() {
	$("#selectable").selectable({
		stop: function() {
			$(".ui-selected", this).each(function() {
				selected_id = $(this).attr("id");
				selectMenu();
			});
		}
	});
});
</script>
<h3>Sort Menu</h3>
<table width="100%">
	<tr>
		<td>Select the menu to sort</td>
		<td>Drag and drop sub-menu to sort</td>
	</tr>
	<tr valign="top">
		<td width="45%">
			<div id="parent-selector">
				<ul id="selectable">
					<li class="ui-state-default" id="0" style="margin-left:5px;">Root
						<input type="hidden" id="value" value="...">
					</li>
					<?php showPosition($menu, 20);?>
				</ul>
			</div>
		</td>
		<td>
			<div id="child-sort"></div>
		</td>
	</tr>
</table>