<table class="list" style="margin-bottom: 0px;">
			<thead>
				<tr>					

					<td class="center" style="min-width: 100px">Product Name</td>
					<td class="center">Viewed</td>					
				</tr>
			</thead>
			<tbody>
				<?php if ($this->items) { ?>			
				<?php foreach($this->items as $val){										
					?>
					<tr>						
						<td><a href="<?php echo HTTP_SERVER.'front/product/detail/product_id/'.$val['product_id']?>"><?php echo $val["model"]?></a></td>
		            	<td class="center"><?php echo $val['viewed'];?></td>		            	
            		</tr>
	          	<?php } ?>	          
          		<?php } else { ?>
			        <tr>
			            <td class="center" colspan="2">Không có k?t qu?</td>
			        </tr>
          		<?php } ?>
			</tbody>
</table>
