<div id="content">
  <div class="breadcrumb"></div>
  <?php if ($this->Items) { ?>
  <div class="news-list">
    <?php foreach ($this->Items as $news) { ?>
    <div>
      <?php if ($news['image']) { ?>
      <div class="image"><a class="fancybox" href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>" title="<?php echo $news['title']; ?>"><img src="<?php echo HTTP_IMAGES . '/' . $news['image']; ?>" width="90" height="90" title="<?php echo $news['title']; ?>" /></a></div>
      <?php } ?>
      <div class="title"><a href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>"><?php echo $news['title']; ?></a></div>
      <div class="summary"><?php echo html_entity_decode($news['summary'], ENT_QUOTES, 'UTF-8'); ?></div>
    </div>
    <?php } ?>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
  </div>
  <?php } ?>
</div>