<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->baseUrl('/admin/order/index/'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br>Lưu</a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/order/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl('/admin/order/index/');?>">????</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('order_entry_name');?></td>
          <td><?php echo $this->formText('full_name', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('order_entry_email');?></td>
           <td><?php echo $this->formText('email', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('order_entry_phone');?></td>
          <td><?php echo $this->formText('phone', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('order_entry_address');?></td>
           <td><?php echo $this->formText('address', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('order_entry_shipping');?></td>
          <td><?php echo $this->formText('shipping', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('order_entry_comment');?></td>
          <td><?php echo $this->formText('comment', null, array('size'=>'50'));?></td>
        </tr>
        <tr>
		  <td><?php echo $this->cmsTranslator('order_entry_status');?></td>
          <td><select name="status">
                  <option value="1" selected="selected"><?php echo $this->cmsTranslator('order_text_enabled'); ?></option>
                  <option value="0"><?php echo $this->cmsTranslator('order_text_disabled'); ?></option>
                </select></td>
        </tr>
      </table>
    </form>
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				full_name: {
					required: true,
			  		minlength: 3,
			  		maxlength: 150,
				},
		    },
		    messages: {		    	
		    	full_name: {
		        	required: "<?php echo $this->cmsTranslator('order_error_name'); ?>",
		        	minlength: "<?php echo $this->cmsTranslator('order_error_name_minlength'); ?>",
		        	maxlength: "<?php echo $this->cmsTranslator('order_error_name_maxlength'); ?>",
				},
			}
		});
	});
	</script>
</div>
</div>