<?php $this->headTitle($this->cmsTranslator('auth_deny_page_title'));?>

<h2><?php echo $this->cmsTranslator('auth_deny_head'); ?></h2>
<hr />

<div class="t_a_bottom"><?php echo $this->cmsTranslator('auth_deny_guide'); ?></div>

<div class="t_a_bottom">
	<button onclick="javascript: history.go(-1);"><span><?php echo $this->cmsTranslator('auth_deny_back_button'); ?></span></button>
</div>
