<?php 
$this->headTitle($this->translator('auth_forgot_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER . '/js/jquery.validate/jquery.validate.min.js');
?>

<form action="<?php echo $this->url(array(), 'core_auth_forgot'); ?>" method="post" id="forgotForm" class="t_a_login_form">
<div class="grid_8 prefix_2 suffix_2">
	<h1>TomatoCMS</h1>
	
	<div class="grid_8 t_a_bottom">
		<div class="grid_4 prefix_2 alpha"><?php echo $this->flashMessenger(); ?></div>
	</div>
	
	<div class="grid_8 t_a_bottom">
		<div class="grid_4 alpha">
			<label><?php echo $this->translator('auth_forgot_user_name'); ?>:</label>
		</div>
		<div class="grid_4 omega">
			<label><?php echo $this->translator('auth_forgot_email'); ?>:</label>
		</div>
	</div>
		
	<div class="grid_8 t_a_bottom">
		<div class="grid_4 alpha">
			<input type="text" name="username" id="username" />
		</div>
		<div class="grid_4 omega">
			<input type="text" name="email" id="email" />
		</div>
	</div>
	
	<div class="grid_8">	
		<div class="grid_4 alpha">
			<a href="<?php echo $this->url(array(), 'core_auth_login'); ?>" class="t_a_ui_helper_arrow_left"><?php echo $this->translator('auth_login_title'); ?></a>
		</div>
		<div class="grid_4 omega">
			<button type="submit" class="t_a_right"><span><?php echo $this->translator('auth_forgot_submit_button'); ?></span></button>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#forgotForm').validate({
		rules: {
			username: {
		  		required: true
			},
			email: {
				required: true
			}
	    },
	    messages: {
	    	username: {
	        	required: "<?php echo $this->translator('auth_forgot_user_name_required'); ?>"
			},
			email: {
	        	required: "<?php echo $this->translator('auth_forgot_email_required'); ?>"
			}
		}
	});
});
</script>
	