<div id="content">
  <div class="breadcrumb"></div>
  <?php if(isset($_SESSION['newseditmode'])) if($_SESSION['newseditmode'] == 'ON'){?>
  	<script>
		
  	</script>
  <?php }?>
  
  <div id="click-and-change-news-tool-bar ui-widget-header ui-corner-all">
  	<div id="btnTurnOnEditMode" role="button" class="state-changable-buttonstate-changable-button ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"><span class="ui-button-text"><a href="<?php echo $this->baseUrl($this->currentController.'/changenewseditmode');?>">Turn News Edit Mode On or Off</a></span></div>
  </div>
  
  <?php if ($this->Item) { ?>
  <div class="news-info">
    <div>
      <div class="title"><?php echo $this->Item['title']; ?></div>
      <div class="summary"><?php echo html_entity_decode($this->Item['summary'], ENT_QUOTES, 'UTF-8'); ?></div>
      <div class="description"><?php echo html_entity_decode($this->Item['description'], ENT_QUOTES, 'UTF-8'); ?></div>
    </div>
    <?php } ?>
  </div>
</div>