<div id="content">
  <div class="breadcrumb"></div>
  <pre>
  </pre>
  <?php if($this->arrayItems){ reset($this->arrayItems);?>
  	<div id="cate-list">
  		<?php if($this->arrHotnews){ ?>
  			<div class="parent-category">
  				<div class="category-body">
  						<div id="latest-news">
  							<img class="latest-news-thumb fl" src="<?php echo $this->arrHotnews[0]['image'];?>"/>
  							<a class="latest-news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$this->arrHotnews[0]['news_id'])?>"><?php echo $this->arrHotnews[0]['title']?></a>
  							<br/>
  							<?php echo html_entity_decode($this->arrHotnews[0]['summary'],ENT_QUOTES,'UTF-8'); ?>
  							<div class="cl"></div>
  						</div>
  						<table id="older-news">
  							<tr>
  							<?php while(!is_null(key($this->arrHotnews))){ if(key($this->arrHotnews) > 3) break; $curHotnews = $this->arrHotnews[key($this->arrHotnews)];?>
  								<td>
  									<?php if(!is_null($curHotnews)){ if(key($this->arrHotnews) > 0){?>
  										<span>
  											<a class="news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$curHotnews['news_id'])?>">
  											<img class="news-thumb" src="<?php echo $curHotnews['image']?>"/><br/><?php echo $curHotnews['title']?></a>
  										</span>
  									<?php }}?>
  								</td>
  							<?php next($this->arrHotnews);}?>
  							</tr>
  						</table>
  				</div>
  				
  				<div style="text-align: right;">
  					<h3><a class="fr" href="<?php echo $this->baseUrl($this->currentController.'/'.'list'.'/category_id/hot-news')?>">Read more...</a></h3>
  				</div>
  			</div><br>
		<?php }?>
  		<?php while(!is_null(key($this->arrayItems))){ $curCategory = $this->arrayItems[key($this->arrayItems)];?>
  				<div class="ui-tabs ui-widget ui-widget-content ui-corner-all">
  					<ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
  						<li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
  							<a href="<?php echo $this->baseUrl($this->currentController.'/'.'list'.'/category_id/'.$curCategory['categoryinfo']['category_id'])?>"><?php echo $curCategory['categoryinfo']['name'];?></a>
  						</li>
  					</ul>
  					<div class="ui-tabs-panel ui-widget-content ui-corner-bottom">
  						<?php if(!is_null($curCategory['news'])){ reset($curCategory['news']);?>
  						<?php while(!is_null(key($curCategory['news'])) && key($curCategory['news']) <3){ $news = current($curCategory['news']);?>
  							<div class="news-box">
  								<a class="news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$news['news_id'])?>">
  								<img class="news-thumb" src="<?php echo $news['image']?>"/><br/><?php echo $news['title']?></a>
  							</div>
  						<?php next($curCategory['news']); }?>
  						<?php }?>
  						<div class="clear"></div>
		  				<div style="text-align: right;">
		  					<h3><a class="fr" href="<?php echo $this->baseUrl($this->currentController.'/'.'list'.'/category_id/'.$curCategory['categoryinfo']['category_id'])?>">Read more...</a></h3>
		  				</div>
	  				</div>
  				</div><br>
  			<?php next($this->arrayItems);?>
  		<?php }?>
  	</div>
  <?php }?>
  
  <pre>
  </pre>
</div>