<div id="content">
  <div class="breadcrumb"></div>
  <pre>
  </pre>
  <?php if($this->arrayItems){ reset($this->arrayItems);?>
  	<div id="cate-list">
  		<?php if($this->arrHotnews){ ?>
  			<div class="parent-category">
  				<div class="category-header">
  					<a href="javascript:void();">Tin nổi bật</a>
  				</div>
  				<div class="category-body">
  						<div id="latest-news">
  							<img class="latest-news-thumb fl" src="<?php echo $this->arrHotnews[0]['image'];?>"/>
  							<a class="latest-news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$this->arrHotnews[0]['news_id'])?>"><?php echo $this->arrHotnews[0]['title']?></a>
  							<br/>
  							<?php echo html_entity_decode($this->arrHotnews[0]['summary'],ENT_QUOTES,'UTF-8'); ?>
  							<div class="cl"></div>
  						</div>
  						<table id="older-news">
  							<tr>
  							<?php while(!is_null(key($this->arrHotnews))){ if(key($this->arrHotnews) > 3) break; $curHotnews = $this->arrHotnews[key($this->arrHotnews)];?>
  								<td>
  									<?php if(!is_null($curHotnews)){ if(key($this->arrHotnews) > 0){?>
  										<span>
  											<a class="news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$curHotnews['news_id'])?>">
  											<img class="news-thumb" src="<?php echo $curHotnews['image']?>"/><br/><?php echo $curHotnews['title']?></a>
  										</span>
  									<?php }}?>
  								</td>
  							<?php next($this->arrHotnews);}?>
  							</tr>
  						</table>
  				</div>
  				
  				<div class="category-footer">
  					<a class="fr" href="<?php echo $this->baseUrl($this->currentController.'/'.'list'.'/category_id/hot-news')?>">Xem nhiều hơn&gt;&gt;</a>
  				</div>
  			</div>
		<?php }?>
  		<?php while(!is_null(key($this->arrayItems))){ $curCategory = $this->arrayItems[key($this->arrayItems)];?>
  				<div class="child-category">
  				<div class="category-header">
  				<a href="<?php echo $this->baseUrl($this->currentController.'/'.'index'.'/category_id/'.$curCategory['categoryinfo']['category_id'])?>"><?php echo $curCategory['categoryinfo']['category_description']['vi_VN']['name'];?></a>
  				</div>
  					<table>
  						<tr>
  						<?php if(!is_null($curCategory['news'])){ reset($curCategory['news']);?>
  						<?php while(!is_null(key($curCategory['news'])) && key($curCategory['news']) <4){ $news = current($curCategory['news']);?>
  							<td>
  								<span>
  								<a class="news-title" href="<?php echo $this->baseUrl($this->currentController.'/'.'detail'.'/news_id/'.$news['news_id'])?>">
  								<img class="news-thumb" src="<?php echo $news['image']?>"/><br/><?php echo $news['title']?></a>
  								</span>
  							</td>
  							
  							<?php next($curCategory['news']); }?>
  							<?php }?>
  						</tr>
  					</table>
  				<div class="category-footer">
  					<a class="fr" href="<?php echo $this->baseUrl($this->currentController.'/'.'list'.'/category_id/'.$curCategory['categoryinfo']['category_id'])?>">Xem nhiều hơn&gt;&gt;</a>
  				</div>
  				</div>
  			<?php next($this->arrayItems);?>
  		<?php }?>
  	</div>
  <?php }?>
  
  <pre>
  </pre>
</div>