<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->referer,
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br>Lưu</a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/linkcron/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl('/admin/linkcron/index/');?>">????</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('linkcron_entry_name');?></td>
          <td><?php echo $this->formText('name', $this->Item['name'], array('size'=>'50'));?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('linkcron_entry_category');?></td>
           <td><div class="scrollbox">
                  <?php $class = 'odd'; ?>
                  <?php foreach ($this->categories as $category) { ?>
                  <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                  <div class="<?php echo $class; ?>">
                    <?php $link_category = explode('-', $this->Item['category_ids']); ?>
                    <?php if (in_array($category['category_id'], $link_category)) { ?>
                    <input type="checkbox" name="link_category[]" value="<?php echo $category['category_id']; ?>" checked="checked" />
                    <?php echo $category['name']; ?>
                    <?php } else { ?>
                    <input type="checkbox" name="link_category[]" value="<?php echo $category['category_id']; ?>" />
                    <?php echo $category['name']; ?>
                    <?php } ?>
                  </div>
                  <?php } ?>
                </div>
                <a onclick="$(this).parent().find(':checkbox').attr('checked', true);"><?php echo $this->cmsTranslator('linkcron_text_select_all');?></a> / <a onclick="$(this).parent().find(':checkbox').attr('checked', false);"><?php echo $this->cmsTranslator('linkcron_text_unselect_all');?></a></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('linkcron_entry_source');?></td>
          <td><?php echo $this->formText('source', $this->Item['source'], array('size'=>'50'));?></td>
        </tr>
        <tr>
           <td><span class="required">*</span> <?php echo $this->cmsTranslator('linkcron_entry_website');?></td>
           <td><select name="link_web_id">
                  <option value=""><?php echo $this->cmsTranslator('linkcron_text_select'); ?></option>
                  <?php foreach ($this->webs as $web) { ?>
                  <?php if($web['link_web_id'] == $this->Item['link_web_id']){ ?>
                  <option value="<?php echo $web['link_web_id']; ?>" selected="selected"><?php echo $web['website_name']; ?></option>
                  <?php } else {?>
                  <option value="<?php echo $web['link_web_id']; ?>"><?php echo $web['website_name']; ?></option>
                  <?php } ?>
                  <?php } ?>
                </select></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('linkcron_entry_frequency');?></td>
          <td><?php echo $this->formText('frequency', $this->Item['frequency'], array('size'=>'10'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('linkcron_entry_priority');?></td>
          <td><?php echo $this->formText('priority', $this->Item['priority'], array('size'=>'10'));?></td>
        </tr>
        <tr>
		  <td><?php echo $this->cmsTranslator('linkcron_entry_status');?></td>
          <td><select name="status">
                  <?php if ($this->Item['status']) { ?>
                  <option value="1" selected="selected"><?php echo $this->cmsTranslator('linkcron_text_enabled'); ?></option>
                  <option value="0"><?php echo $this->cmsTranslator('linkcron_text_disabled'); ?></option>
                  <?php } else { ?>
                  <option value="1"><?php echo $this->cmsTranslator('linkcron_text_enabled'); ?></option>
                  <option value="0" selected="selected"><?php echo $this->cmsTranslator('linkcron_text_disabled'); ?></option>
                  <?php } ?>
                </select></td>
        </tr>
      </table>
    </form>
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				name: {
					required: true,
			  		minlength: 3,
			  		maxlength: 150,
				},
				source: {
					required: true,
			  		minlength: 3,
			  		maxlength: 150,
				},
				link_web_id: {
					required: true,
				},
		    },
		    messages: {		    	
		    	name: {
		        	required: "<?php echo $this->cmsTranslator('linkcron_error_name'); ?>",
		        	minlength: "<?php echo $this->cmsTranslator('linkcron_error_name_minlength'); ?>",
		        	maxlength: "<?php echo $this->cmsTranslator('linkcron_error_name_maxlength'); ?>",
				},
		    	source: {
		        	required: "<?php echo $this->cmsTranslator('linkcron_error_source'); ?>",
		        	minlength: "<?php echo $this->cmsTranslator('linkcron_error_source_minlength'); ?>",
		        	maxlength: "<?php echo $this->cmsTranslator('linkcron_error_source_maxlength'); ?>",
				},
				link_web_id: {
					required: "<?php echo $this->cmsTranslator('linkcron_error_link_web'); ?>",
				},
			}
		});
	});
	</script>
</div>
</div>