<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Edit - link
		$btnEdit = $this->cmsButton(
						'Edit Item',
						$this->baseUrl($this->currentController . '/edit/link_cron_id/' . $this->Item['link_cron_id']),
						HTTP_IMAGES . '/icon/icon-32-edit.png',
						'link'
					);
										
		//2. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->referer,
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right"><?php echo $btnEdit;?><?php echo $btnCancel;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/linkcron/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl('/admin/linkcron/index/');?>">????</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td><?php echo $this->cmsTranslator('linkcron_entry_name');?></td>
          <td><?php echo $this->Item['name'];?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('linkcron_entry_category');?></td>
           <td><ul>
                  <?php foreach ($this->categories as $category) { ?>
                    <?php $link_category = explode('-', $this->Item['category_ids']); ?>
                    <?php if (in_array($category['category_id'], $link_category)) { ?>
                    	<li><?php echo $category['name']; ?></li>
                    <?php } ?>                  
                  <?php } ?>
                </ul></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('linkcron_entry_source');?></td>
          <td><?php echo $this->Item['source'];?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('linkcron_entry_website');?></td>
           <td><?php foreach ($this->webs as $web) { ?>
                  <?php if($web['link_web_id'] == $this->Item['link_web_id']){ ?>
                  	<?php echo $web['website_name']; ?>
                  <?php }?>
               <?php } ?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('linkcron_entry_frequency');?></td>
          <td><?php echo $this->Item['frequency'];?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('linkcron_entry_priority');?></td>
          <td><?php echo $this->Item['priority'];?></td>
        </tr>
        <tr>
		  <td><?php echo $this->cmsTranslator('linkcron_entry_status');?></td>
          <td><?php if($this->Item['status'] == 1){
          		echo $this->cmsIconButton('Active', HTTP_IMAGES . '/icon/icon_16_active.png');
          	  }else{
          		echo $this->cmsIconButton('Inactive', HTTP_IMAGES . '/icon/icon_16_inactive.png');
          	  }?></td>
        </tr>
      </table>
    </form>
</div>
</div>