<?php echo $this->doctype();?>
<html>
<head>
<?php echo $this->headTitle();?>
<?php echo $this->headMeta();?>
<?php echo $this->headLink();?>
<?php echo $this->headStyle();?>
<?php echo $this->headScript();?>
</head>
<body>
<div id="container">
<?php echo $this->render('_partial/_header.phtml');?>

<div id="col-left">
<?php echo $this->layout()->content ?>
</div>

<div id="col-right">
<?php echo $this->render('_partial/_left.phtml');?>
</div>

<?php echo $this->render('_partial/_footer.phtml');?>
</div>
</body>
</html>