<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->headScript() ?>
</head>
<body>
	<!-- Container_Begin -->
	<div id="container">
    	<!-- Header_Begin -->
        <div id="header">
            <div id="banner">
           	  <div id="banner_img"></div>
              <div id="banner_text">Bring you the easiest way...</div>
              <a href="admin/index">Admin</a>
          </div>
        	<div id="top-menu">
            	<ul>
                	<li><a href="#">Home Page</a>
                    	<ul>
                        	<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </li>
                    <li><a href="#">About</a>
                    	<ul>
                        	<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Contact</a>
                    	<ul>
                        	<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </li>
                  <li><a href="#">Services</a>
                   	  <ul>
                       	  <li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                      </ul>
                  </li>
                    <li><a href="#">Forum</a>
                    	<ul>
                        	<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </li>
                    <li><a href="#">FAQs</a>
                    	<ul>
                        	<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <!-- Header_End -->
        </div>
        
        <!-- Main_Begin -->
        <div id="main">
        	<!-- Left_Begin -->
        	<div id="left">
                <div class="box">
                	<div class="box-tilte">
                    	Menu_1
                    </div>                    
                    <div class="box-body">
                    	<ul>
                    		<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </div>
                </div>
                <div class="box">
                	<div class="box-tilte">
                    	Menu_2
                    </div>                    
                    <div class="box-body">
                    	<ul>
                    		<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </div>
                </div>
                <div class="box">
                	<div class="box-tilte">
                    	Menu_3
                    </div>                    
                    <div class="box-body">
                    	<ul>
                    		<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </div>
                </div>
                <div class="box">
                	<div class="box-tilte">
                    	Menu_4
                    </div>                    
                    <div class="box-body">
                    	<ul>
                    		<li><a href="#">SubMenu_1</a></li>
                            <li><a href="#">SubMenu_2</a></li>
                            <li><a href="#">SubMenu_3</a></li>
                            <li><a href="#">SubMenu_4</a></li>
                            <li><a href="#">SubMenu_5</a></li>
                        </ul>
                    </div>
                </div>
            <!-- Left_End -->
            </div>
            
            <!-- Left_Begin -->
            <div id="center">
            Main Content Is Put Here.
            <!-- Left_End -->
            </div>
            
      <!-- Left_Begin -->
            <div id="right">
            	<div class="box">
                	<div class="box-tilte">
                    	Login
                    </div>                    
                    <div class="box-body">
                    	<div class="box-body-text">
                    	<form name="frmLogin" action="#" method="post">
                        User Name: <br /><input type="text" /><br />
                        Password: <br /><input type="password" /><input type="submit" value="OK" /><br />
                        <input type="checkbox" name="chkKeepSignIn"/> Keep me signed in. <br />
                        <a href="#">Forget your password?</a>                       
                        </form>
                        </div>
                    </div>
              </div>
           	  <div class="box">
                	<div class="box-tilte">
                    	<a href="#">News_1</a>
                    </div>                    
                    <div class="box-body">
                    	<div class="box-body-text">
                    	Some descriptions for news1 is put here... Some Text Here Some Text Here Some Text Here Some Text Here Some Text Here Some Text Here ....
                        </div>
                    </div>
              </div>
            	
                <div class="box">
                	<div class="box-tilte">
                    	<a href="#">H? tr? tr?c tuy?n</a>
                    </div>                    
                    <div class="box-body">
                    	<div class="box-body-text">
                    	<a href="ymsgr:sendIM?khanhhuyh3qt@yahoo.com"><img border="0" src="http://presence.msg.yahoo.com/online?u=Yahoo!ID&amp;amp;m=g&amp;amp;t=ImageNo&amp;amp;l=us"></a> Ngô Vi?t Khánh Huy<br />
                        <a href="ymsgr:sendIM?ngonlua_thienduong@yahoo.com"><img border="0" src="http://presence.msg.yahoo.com/online?u=Yahoo!ID&amp;amp;m=g&amp;amp;t=ImageNo&amp;amp;l=us"></a> Tôn Th?t Hi?n
                        </div>
                    </div>
                </div>
                <div class="box">
                	<div class="box-tilte">
                    	<a href="#">Statistics</a>
                    </div>                    
                    <div class="box-body">
                    	<div class="box-body-text">
                    	Today: <br />
                        Yesterday:<br />
                        This Week: <br />
                        This Month:<br />
                        This Year: <br />
                        Total:<br />
                        </div>
                    </div>
                </div>
            <!-- Left_End -->
            </div>
        <!-- Main_End -->
        </div>
        
        <!-- Footer_Begin -->
        <div id="footer">&copy;Copyright: Group C&amp;C13 - University of Information Technology
          <!-- Footer_End -->
        </div>
      <!-- Container_End -->
    </div>
</body>
</html>
	
