<div id="content">
  <div class="breadcrumb"></div>
  
	<pre>
	<?php print_r($this->testparam);?>
	</pre>
  
  <?php if ($this->Items) { ?>
  <div class="news-list">
    <?php foreach ($this->Items as $news) { ?>
    <div class="editable-item" newsid="<?php echo $news['news_id'];?>">
      <?php if ($news['image']) { ?>
      <div class="image">
      	<a class="fancybox" href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>" title="<?php echo $news['title']; ?>"><img src="<?php echo HTTP_IMAGES . '/' . $news['image']; ?>" width="90" height="90" title="<?php echo $news['title']; ?>" /></a>
      </div>
      <?php } ?>
      <div class="title"><a href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>"><?php echo $news['title']; ?></a></div>
      <div class="summary"><?php echo html_entity_decode($news['summary'], ENT_QUOTES, 'UTF-8'); ?></div>
    </div>
    <?php } ?>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
  </div>
  <?php } ?>
  <div id="highlighter-region">
  </div>
  <div id="contextMenu">
  <form id='news-context-menu' name='contextMenu' method='post' action=''>
  <input type='hidden' name='news-id' value=''/>
  <ul id="contextMenu_01">
  	<li><a href="javascript:void();" name="news-add"><span class="add-menu-item">Add</span></a></li>
  	<li><a href="javascript:void();" name="news-edit"><span class="edit-menu-item">Edit</span></a></li>
  	<li><a href="javascript:void();" name="news-remove"><span class="remove-menu-item">Remove</span></a></li>
  	<li><a href="javascript:void();" name="news-detail"><span class="detail-menu-item">Show detail</span></a></li>
  </ul>
  </form>
  </div>
</div>