<script type="text/javascript">
$(document).ready(function(){
	var _currentNewsID;
	//
	$('#contextMenu').hide();
	
	$('.editable-item').mouseenter(function(e){
		if($('#contextMenu').css('display')=='block') return false;
		e.stopPropagation();
		_currentNewsID = $(this).attr('newsid');
		var offset = $(this).offset();
		$('#highlighter-region').css('position','absolute');
		$('#highlighter-region').css('top', offset.top);
		$('#highlighter-region').css('left', offset.left);
		$('#highlighter-region').css('width',$(this).width());
		$('#highlighter-region').css('height',$(this).height());
		$('#highlighter-region').css('display','block');
		
	});
	
	$('#highlighter-region').click(function(e){
		e.stopPropagation();
		$('#contextMenu').css('top',e.pageY);
		$('#contextMenu').css('left',e.pageX);
		$('#contextMenu').find('input[name=news-id]').val(_currentNewsID);
		$('#contextMenu').show();
		
	});
	
	$('#remove-menu-item_01').click(function(){
		var actionurl = $("#delete-action").val();
		$('#news-context-menu').attr('action',actionurl);
		$('#news-context-menu').submit();
	});
	
	$('#add-menu-item_01').click(function(){
		$('#add-form').dialog("open");
	});
	
	$('#edit-menu-item_01').bind('click',function(){
		alert(_currentNewsID);		
		$.ajax({
			type:'POST',
			url:'<?php echo $this->baseUrl('admin/services/getnews')?>',
			data:{newsid:_currentNewsID},
			dataType:'json',
			success:function(json){
				if(json.success){
					$('#edit-news-form input[name=save-news-id]').val(json.news_id);
					$('#edit-news-form img[name=image]').attr('src',json.image);
					$('#edit-news-form input[name=sort-order]').val(json.sort_order);
					$('#edit-news-form select[name=status]').val(json.status);
					if(json.en_language)
					{
						$('#edit-news-form fieldset input[name=en_title]').val(json.en_title);
						$('#edit-news-form fieldset textarea[name=en_summary]').val(json.en_summary);
						$('#edit-news-form fieldset textarea[name=en_description]').val(json.en_description);
						$('#edit-news-form fieldset input[name=en_metakeywords]').val(json.en_meta_keywords);
						$('#edit-news-form fieldset input[name=en_metadescription]').val(json.en_meta_description);
					}
					if(json.vi_language)
					{
						$('#edit-news-form fieldset input[name=vi_title]').val(json.vi_title);
						$('#edit-news-form fieldset textarea[name=vi_summary]').val(json.vi_summary);
						$('#edit-news-form fieldset textarea[name=vi_description]').val(json.vi_description);
						$('#edit-news-form fieldset input[name=vi_metakeywords]').val(json.vi_meta_keywords);
						$('#edit-news-form fieldset input[name=vi_metadescription]').val(json.vi_meta_description);
					}
					alert(json.success);
				}
				if(json.error){
					alert(json.error);
				}
			}			
		});
		

		$('#edit-form').dialog("open");
	});
});
$(function(){
	//
	$(document).click(function(){
		$('#highlighter-region').hide();
		$('#contextMenu').hide();
	});
	
	//
	$('#add-form').dialog({
			autoOpen:false,
			modal:true,
			width:500,
			height:500,
			buttons: {
				"Save": function() {
					$('#add-news-form').submit();
				},
				Cancel: function() {
					$( this ).dialog( "close" );
				}
			}});
	
	//
	$('#edit-form').dialog({
		autoOpen:false,
		modal:true,
		width:500,
		height:500,
		buttons:{
			"Save":function(){
				$('#edit-news-form').submit();
			},
			Cancel:function(){
				$(this).dialog("close");
			}
		}
	});
});
</script>
<div id="content">
  <div class="breadcrumb"></div>
  <?php echo $_SESSION["delete_news_message"]; $_SESSION["delete_news_message"] = "";?>
  <?php echo $_SESSION["add_news_message"]; $_SESSION["add_news_message"] = "";?>
  <?php echo $_SESSION["edit_news_message"]; $_SESSION["edit_news_message"] = "";?>
	<pre>
	<?php print_r($this->testparam);?>
	</pre>
  <?php echo date("m-d-Y H:i:s");?>
  <?php if ($this->Items) { ?>
  <div class="news-list">
    <?php foreach ($this->Items as $news) { ?>
    <div class="editable-item" newsid="<?php echo $news['news_id'];?>">
      <?php if ($news['image']) { ?>
      <div class="image">
      	<a class="fancybox" href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>" title="<?php echo $news['title']; ?>"><img src="<?php echo HTTP_IMAGES . '/' . $news['image']; ?>" width="90" height="90" title="<?php echo $news['title']; ?>" /></a>
      </div>
      <?php } ?>
      <div class="title"><a href="<?php echo $this->baseUrl($this->currentController . '/detail/news_id/' . $news['news_id']);?>"><?php echo $news['title']; ?></a></div>
      <div class="summary"><?php echo html_entity_decode($news['summary'], ENT_QUOTES, 'UTF-8'); ?></div>
    </div>
    <?php } ?>
    <div class="pagination">
    <?php 
    	$currentUrl = $this->baseUrl($this->currentController . '/index');
    	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml', array('currentUrl'=>$currentUrl));
    ?>
    </div>
  </div>
  <?php } ?>
  <div id="highlighter-region">
  </div>
  <div id="contextMenu">
  <form id='news-context-menu' name='contextMenu' method='post' action="">
  <input type='hidden' name='news-id' value=''/>
  <input type="hidden" id="delete-action" value="<?php echo $this->baseUrl('admin/newnews/delete');?>">
  <ul id="contextMenu_01">
  	<li><a href="javascript:void();"><span class="add-menu-item" id="add-menu-item_01">Add</span></a></li>
  	<li><a href="javascript:void();"><span class="edit-menu-item" id="edit-menu-item_01">Edit</span></a></li>
  	<li><a href="javascript:void();"><span class="remove-menu-item" id="remove-menu-item_01">Remove</span></a></li>
  	<li><a href="javascript:void();"><span class="detail-menu-item" id="detail-menu-item_01">Show detail</span></a></li>
  </ul>
  </form>
  </div>
  
  <div id="add-form" title="Add News Dialog">
  <form id="add-news-form" name="add-news-form" method="post" action="<?php echo $this->baseUrl($this->currentController.'/add')?>">
  	<fieldset>
 	<legend>Thông tin chung</legend>
 	<span style="width:100px; display:inline-block">Image</span><input type="text" name="image" size="60"><br/>
 	<span style="width:100px; display:inline-block">Sort order</span><input type="text" name="sort-order" size="3"><br/>
 	<span style="width:100px; display:inline-block">Status</span><select name="status"><option value="1">Enable</option><option value="0">Disable</option></select><br/>
 	</fieldset>
 	
 	<fieldset>
 	<legend>Phiên bản tiếng việt</legend>
 	Title<br/><input type="text" name="vi_title" size="83"><br/>
 	Summary<br/><textarea cols="80" rows="2" name="vi_summary"></textarea><br/>
 	Description<br/><textarea cols="80" rows="6" name="vi_description"></textarea><br/>
 	Meta keywords<br/><input type="text" name="vi_metakeywords" size="60"><br/>
 	Meta description<br/><input type="text" name="vi_metadescription" size="60"><br/>
 	</fieldset>
 	
 	<fieldset>
 	<legend>Phiên bản tiếng anh</legend>
 	Title<br/><input type="text" name="en_title" size="83"><br/>
 	Summary<br/><textarea cols="80" rows="2" name="en_summary"></textarea><br/>
 	Description<br/><textarea cols="80" rows="6" name="en_description"></textarea><br/>
 	Meta keywords<br/><input type="text" name="en_metakeywords" size="60"><br/>
 	Meta description<br/><input type="text" name="en_metadescription" size="60"><br/>
 	</fieldset>
 	
 	</form>
  </div>
  
  <div id="edit-form" title="Edit News Dialog">
  <form id="edit-news-form" name="edit-news-form" method="post" action="<?php echo $this->baseUrl($this->currentController.'/save')?>">
  	<input type="hidden" name="save-news-id" value=""/>
  	<fieldset>
 	<legend>Thông tin chung</legend>
 	<span style="width:100px; display:inline-block">Image</span><img src="" name="image"><a href="javascript:void();" id="edit-news-change-image">Change</a><br/>
 	<span style="width:100px; display:inline-block">Sort order</span><input type="text" name="sort-order" size="3"><br/>
 	<span style="width:100px; display:inline-block">Status</span><select name="status"><option value="1">Enable</option><option value="0">Disable</option></select><br/>
 	</fieldset>
 	
 	<fieldset>
 	<legend>Phiên bản tiếng việt</legend>
 	Title<br/><input type="text" name="vi_title" size="83"><br/>
 	Summary<br/><textarea cols="80" rows="2" name="vi_summary"></textarea><br/>
 	Description<br/><textarea cols="80" rows="6" name="vi_description"></textarea><br/>
 	Meta keywords<br/><input type="text" name="vi_metakeywords" size="60"><br/>
 	Meta description<br/><input type="text" name="vi_metadescription" size="60"><br/>
 	</fieldset>
 	
 	<fieldset>
 	<legend>Phiên bản tiếng anh</legend>
 	Title<br/><input type="text" name="en_title" size="83"><br/>
 	Summary<br/><textarea cols="80" rows="2" name="en_summary"></textarea><br/>
 	Description<br/><textarea cols="80" rows="6" name="en_description"></textarea><br/>
 	Meta keywords<br/><input type="text" name="en_metakeywords" size="60"><br/>
 	Meta description<br/><input type="text" name="en_metadescription" size="60"><br/>
 	</fieldset>
 	
 	</form>
  </div>
  
</div>