<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Cancel - link
		$btnCancel = $this->cmsButton(
						$this->cmsTranslator('user_add_cancel_button'),
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right">
		<div><a onclick="$('#form').submit();"><img src="<?php echo HTTP_IMAGES . '/icon/icon-32-save.png';?>"/><br><?php echo $this->cmsTranslator('user_add_save_button');?></a></div>
		<?php echo $btnCancel;?>
	</div>
</div>
<div class="breadcrumb">
	<a href="<?php echo HTTP_SERVER . '/admin/userpermission/index/';?>">Group Manager</a>
	<a href="<?php echo HTTP_SERVER . '/admin/user/index/';?>">Member Manager</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('user_name'); ?></td>
          <td><?php echo $this->formText('username', $this->Item['username'], array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('user_first_name'); ?></td>
          <td><?php echo $this->formText('firstname', $this->Item['firstname'], array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('user_last_name'); ?></td>
          <td><?php echo $this->formText('lastname', $this->Item['lastname'], array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('user_email'); ?></td>
          <td><?php echo $this->formText('email', $this->Item['email'], array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td>Birthday:</td>
          <td><?php echo $this->formText('birthday', $this->Item['birthday'], array('class'=>'date'));?></td>
        </tr>
        <tr>
          <td>Avatar:</td>
          <td><?php echo $this->formText('avatar', $this->Item['avatar'], array('readonly'=>'readonly', 'onclick'=>'openKCFinder(this)', 'size'=>'60'));?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('user_group'); ?></td>
          <td><?php echo $this->formSelect('user_group_id', $this->Item['user_group_id'], null, $this->group);?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('user_password'); ?>
          	<span class="help"><?php echo $this->cmsTranslator('user_password_guide'); ?></span></td>
          <td><?php echo $this->formPassword('password', '', array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->cmsTranslator('user_confirm_password'); ?>
          	<span class="help"><?php echo $this->cmsTranslator('user_confirm_password_guide'); ?></span></td>
          <td><?php echo $this->formPassword('confirmPassword', '', array('size'=>'50'));?></td>
        </tr>
        <tr>
          <td>Status: </td>
          <td><label for="status-0"><input id="status-0" type="radio" value="0" name="status">Inactive</label>
          	<label for="status-1"><input id="status-1" type="radio" value="1" name="status"  checked="checked">Active</label></td>
        </tr>
        <tr>
           <td>Sign:</td>
           <td><?php echo $this->formTextarea('sign', $this->Item['sign'], array('rows'=>'8', 'cols'=>'50'));?></td>
        </tr>
      </table>
    </form>
	<!-- khởi tạo editor -->
	<?php echo $this->cmsEditor(array('sign'), array());?>
	<!-- Ngày tháng -->
	<script type="text/javascript" src="<?php echo HTTP_PUBLIC . '/javascript/jquery/ui/jquery-ui-timepicker-addon.js';?>"></script> 
	<script type="text/javascript">
	$('.date').datepicker({dateFormat: 'yy-mm-dd'});
	$('.datetime').datetimepicker({
		dateFormat: 'yy-mm-dd',
		timeFormat: 'h:m'
	});
	$('.time').timepicker({timeFormat: 'h:m'});
	</script>
	<script type="text/javascript">
	function openKCFinder(field) {
	    window.KCFinder = {
	        callBack: function(url) {
	            window.KCFinder = null;
	            field.value = url;
	        }
	    };
	    window.open('<?php echo HTTP_PUBLIC;?>/scripts/kcfinder/browse.php?type=images&dir=images', 'kcfinder_textbox',
	        'status=0, toolbar=0, location=0, menubar=0, directories=0, ' +
	        'resizable=1, scrollbars=0, width=800, height=600'
	    );
	}
	</script>
	<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * Validate form
		 */
		$('#form').validate({
			rules: {				
				username: {
			  		required: true,
			  		minlength: 3,
			  		maxlength: 20,
			  		remote: '<?php echo $this->baseUrl($this->currentController . '/check/check_type/username'); ?>'
				},
				email: {
					required: true,
					email: true,
					remote: '<?php echo $this->baseUrl($this->currentController . '/check/check_type/email'); ?>'
				},
				password: {
			  		required: true,
			  		minlength: 5
				},
				confirmPassword: {
					equalTo: '#password'
				},
				user_group_id: {
					required: true,
					min: 1
				}
		    },
		    messages: {		    	
		    	username: {
		        	required: "<?php echo $this->cmsTranslator('user_user_name_required'); ?>",
					minlength: "<?php echo $this->cmsTranslator('user_user_name_minlength'); ?>",
					maxlength: "<?php echo $this->cmsTranslator('user_user_name_maxlength'); ?>",
					remote: "<?php echo $this->cmsTranslator('user_user_name_exist'); ?>"
				},
				email: { 
		        	required: "<?php echo $this->cmsTranslator('user_email_required'); ?>",
		        	email: "<?php echo $this->cmsTranslator('user_email_invalid'); ?>",
			        remote: "<?php echo $this->cmsTranslator('user_email_exist'); ?>"
		    	},
		    	password: {
					required: "<?php echo $this->cmsTranslator('user_password_required'); ?>",
					minlength: "<?php echo $this->cmsTranslator('user_password_minlength'); ?>"				
				},
				confirmPassword: {
					equalTo: "<?php echo $this->cmsTranslator('user_confirm_password_error'); ?>"
				},
				user_group_id: {
					required: "<?php echo $this->cmsTranslator('user_group_required'); ?>",
					min: "<?php echo $this->cmsTranslator('user_group_required'); ?>"
				}
			}
		});
	});
	</script>
</div>
</div>