<script>
</script>

<div id="link-selector">
<div id="link-validation" class="ui-state-error"></div>
<br>
Select address where this item link to:
<br>
<table border="0px;" width="100%">
	<form>
		<tr>
			<td width="120px;">
				<input type="radio" name="chkLinkType" value="0"/>Special Place
			</td>
			<td>
				<select name="cboSpecialPlace">
					<option>Home Page</option>
					<option>News</option>
					<option>Product</option>
				</select>
			</td>
		</tr>
		<tr>
			<td width="120px;">
				<input type="radio" name="chkLinkType" value="1"/>Category
			</td>
			<td>
				<select name="cboCategory">
					<option>Home Page</option>
					<option>News</option>
					<option>Product</option>
				</select>
			</td>
		</tr>
		<tr>
			<td width="120px;">
				<input type="radio" name="chkLinkType" value="2"/>Site
			</td>
			<td>
				<select name="cboSite">
					<option>Home Page</option>
					<option>News</option>
					<option>Product</option>
				</select>
			</td>
		</tr>
	</form>
</table>
</div>