<?php
$menu = $this->item;
if(isset($this->selected) && $this->selected != null) {
	$selected = $this->selected['parent'];
	$position = $this->selected['position'];
} else {
	$selected = 0;
	$position = "...";
}

function showPosition($menu, $margin_left) {
	foreach($menu['children'] as $sub) {
		echo '<li class="ui-state-default" id="'.$sub['id'].'" style="margin-left:'.$margin_left.'px;">'.$sub['name'];
		echo '<input type="hidden" id="value" value="'.$sub['position'].$sub['name'].'"></li>';
		showPosition($sub, $margin_left + 25);
	}
}
?>
<script>
function errorPosition(value) {
	$("#position-validation").html(value);
}

function selectElement(id) {
	$('#selectable').find('li').removeClass('ui-selected');
	$('#selectable').find('#' + '<?php echo $selected;?>').addClass('ui-selected');
}

$(function() {
	selectElement('0');
	
	$("#selectable").selectable({
		stop: function() {
			$("#select-result").empty();
			$(".ui-selected", this).each(function() {
				var value =  $(this).children('input').val();
				var id = $(this).attr("id");
				$("input[name=txtSelectedPosition]").val(value);
				$("input[name=txtSelectedParent]").val(id);
			});
		}
	});
});
</script>
<div id="position-selector">
	Selected Position: 
	<input type="text" disabled="disabled" name="txtSelectedPosition" size="57" value="<?php echo $position;?>"/>
	<input type="hidden" name="txtSelectedParent" value="<?php echo $selected;?>">
	<br>
	<div id="position-validation" class="ui-state-error"></div>
	<br>
	Choose parent menu for this item:
	<ul id="selectable">
		<li class="ui-state-default" id="0" style="margin-left:5px;">Root
			<input type="hidden" id="value" value="...">
		</li>
		<?php showPosition($menu, 25);?>
	</ul>
</div>