<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Edit - link
		$btnEdit = $this->cmsButton(
						'Edit Item',
						$this->baseUrl($this->currentController . '/edit/invoice_id/' . $this->Item['invoice_id']),
						HTTP_IMAGES . '/icon/icon-32-edit.png',
						'link'
					);
										
		//2. Cancel - link
		$btnCancel = $this->cmsButton(
						'Cancel',
						$this->referer,
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right"><?php //echo $btnEdit;?><?php echo $btnCancel;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/invoice/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl('/admin/invoice/index/');?>">????</a>
</div>
	<div class="content">
      <div class="vtabs"><a href="#tab-order">Đơn hàng</a><a href="#tab-payment">Chi tiết thanh toán</a><a href="#tab-product">Sản phẩm</a><a href="#tab-history">Comment đơn hàng</a></div>
      <div id="tab-order" class="vtabs-content">
        <table class="form">
          <tr>
            <td>ID đơn hàng:</td>
            <td>#<?php echo $this->Item['invoice_id']; ?></td>
          </tr>
          <tr>
            <td>Cửa hàng:</td>
            <td><a onclick="window.open('<?php echo $this->baseUrl('/front');?>');"><u>UIT</u></a></td>
          </tr>
          <tr>
            <td>Khách hàng:</td>
            <td><?php echo $this->Item['full_name']; ?></td>
          </tr>
          <tr>
            <td>Email:</td>
            <td><?php echo $this->Item['email']; ?></td>
          </tr>
          <tr>
            <td>Điện thoại:</td>
            <td><?php echo $this->Item['phone']; ?></td>
          </tr>
          <tr>
            <td>Ngày tạo:</td>
            <td><?php echo date('d-m-Y H:i:s', strtotime($this->Item['date_added'])); ?></td>
          </tr>
        </table>
      </div>
      <div id="tab-payment" class="vtabs-content">
        <table class="form">
          <tr>
            <td>Địa chỉ:</td>
            <td><?php echo $this->Item['address']; ?></td>
          </tr>
          <tr>
            <td>Vận chuyển:</td>
            <td><?php echo $this->Item['shipping']; ?></td>
          </tr>
        </table>
      </div>
      <div id="tab-product" class="vtabs-content">
        <table id="product" class="list">
          <thead>
            <tr>
              <td class="left">Sản phẩm</td>
              <td class="right">Số lượng</td>
              <td class="right">Giá</td>
              <td class="right">Tổng tiền</td>
            </tr>
          </thead>
          <?php foreach ($this->Items as $product) { ?>
          <?php $total = 0;?>
          <tbody id="product-row<?php echo $product['product_id']; ?>">
            <tr>
              <td class="left"><?php if ($product['product_id']) { ?>
                <a target="_blank" href="<?php echo $this->baseUrl('/front/product/detail/product_id/' . $product['product_id']);?>"><?php echo $product['name']; ?></a>
                <?php } else { ?>
                <?php echo $product['name']; ?>
                <?php } ?></td>
              <td class="right"><?php echo $product['quantity']; ?></td>
              <td class="right"><?php echo $product['price']; ?>đ</td>
              <td class="right"><?php echo $product['price']*$product['quantity'] ; ?>đ</td>
              <?php $total += $product['price']*$product['quantity'];?>
            </tr>
          </tbody>
          <?php } ?>
          <tbody id="totals">
            <tr>
              <td colspan="3" class="right">Thành tiền:</td>
              <td class="right"><?php echo $total;?>đ</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div id="tab-history" class="vtabs-content">
        <div id="history"></div>
        <table class="form">
          <tr>
            <td>Comment</td>
            <td><textarea name="comment" cols="40" rows="8" style="width: 99%"><?php echo $this->Item['comment']; ?></textarea></td>
          </tr>
        </table>
      </div>
    </div>
</div>
<script type="text/javascript"><!--
$.fn.tabs = function() {
	var selector = this;
	
	this.each(function() {
		var obj = $(this); 
		
		$(obj.attr('href')).hide();
		
		$(obj).click(function() {
			$(selector).removeClass('selected');
			
			$(selector).each(function(i, element) {
				$($(element).attr('href')).hide();
			});
			
			$(this).addClass('selected');
			
			$($(this).attr('href')).show();
			
			return false;
		});
	});

	$(this).show();
	
	$(this).first().click();
};
$('.vtabs a').tabs();
//--></script> 