<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/menu/")?>">Menu Manager</a><br>	
</div>
<h4>Menu Item Edit (by ThiVT)</h4>
<form method="post" name="menumanagerForm">
	 <table border="1" align="right">
		<tr>
			<td align="right"><input align="right" type="button" name="btnCopy" id="btnCopy" onClick="window.location.href = '<?php echo $this->baseUrl("/admin/menu/menucopy")?>'" value="Copy" />
			<input align="right" type="button" name="btnDelete" id="btnDelete" value="Delete" />
			<input align="right" type="button" name="btnEdit" id="btnEdit" onClick="window.location = '<?php echo $this->baseUrl("/admin/menu/menuedit")?>'" value="Edit" />
			<input align="right" type="button" name="btnNew" id="btnNew" value="New" />			
			<input align="right" type="button" name="btnHelp" id="btnHelp" value="Help" /></td>
		</tr>
  </table><br><br>
<table border="1">
	<tr>
		<th width="3%">#</th>
		<th width="3%">&nbsp;</th>
		<th width="10%">Title</th>
		<th width="10%">Type</th>
		<th width="10%">Menu item(s)</th>
		<th width="10%">#Published</th>
		<th width="10%">#Unpublished</th>
		<th width="10%">#Trash</th>
		<th width="10%">#Modules</th>
		<th width="10%">ID</th>
	</tr>
	<tbody>
		<tr class="row0">
			<td width="3%">1</td>
			<td width="3%"><input type="radio" id="cb0" name="cid[]"
				value="en_GB" onclick="isChecked(this.checked);"/></td>
			<td width ="10%" align="center">Main Menu</td>
			<td width ="10%" align="center">mainMenu</td>
			<td width ="10%" align="center">3</td>
			<td width ="10%" align="center">2</td>
			<td width ="10%" align="center">.</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">1</td>
		</tr>
		<tr class="row0">
			<td width="3%">2</td>
			<td width="3%"><input type="radio" id="cb0" name="cid[]"
				value="en_GB" onclick="isChecked(this.checked);"/></td>
			<td width ="10%" align="center">Lelf Menu</td>
			<td width ="10%" align="center">leftMenu</td>
			<td width ="10%" align="center">5</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">.</td>
			<td width ="10%" align="center">0</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">2</td>
		</tr>
	</tbody>
</table>
</form>