<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php		
		//1. Edit - link
		$btnEdit = $this->cmsButton(
						$this->cmsTranslator('link_button_edit'),
						$this->baseUrl($this->currentController . '/edit/link_id/' . $this->Item['link_id']),
						HTTP_IMAGES . '/icon/icon-32-edit.png',
						'link'
					);
										
		//2. Cancel - link
		$btnCancel = $this->cmsButton(
						$this->cmsTranslator('link_button_cancel'),
						$this->baseUrl($this->currentController . '/index'),
						HTTP_IMAGES . '/icon/icon-32-cancel.png',
						'link'
					);
		
	?>
	<div class="right"><?php echo $btnEdit;?><?php echo $btnCancel;?></div>
</div>
<div class="breadcrumb">
	<a href="<?php echo $this->baseUrl('/admin/link/index/');?>">????</a>
	<a href="<?php echo $this->baseUrl('/admin/link/index/');?>">????</a>
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" > 
      <table class="form">
        <tr>
          <td><?php echo $this->cmsTranslator('link_entry_title');?></td>
          <td><?php echo $this->Item['title'];?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('link_entry_slug');?></td>
          <td><?php echo $this->Item['slug'];?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('link_entry_description'); ?></td>
          <td><?php echo $this->Item['description'];?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('link_entry_category');?></td>
           <td>
                  <?php foreach ($this->categories as $category) { ?>
                    <?php if (in_array($category['category_id'], $this->link_category)) { ?>
                    <p><?php echo $category['name']; ?></p>
                    <?php } ?>
                  <?php } ?></td>
        </tr>
         <tr>
          <td><?php echo $this->cmsTranslator('link_entry_image');?></td>
          <td><?php echo $this->Item['image'];?></td>
        </tr>
        <tr>
          <td><?php echo $this->cmsTranslator('link_entry_source');?></td>
          <td><?php echo $this->Item['link_source'];?></td>
        </tr>
        <tr>
           <td><?php echo $this->cmsTranslator('link_entry_website');?></td>
           <td>
                  <?php foreach ($this->webs as $web) { ?>
                  <?php if($web['link_web_id'] == $this->Item['link_web_id']){ ?>
                  	<?php echo $web['website_name']; ?>
                  <?php } ?>
                  <?php } ?></td>
        </tr>
        <tr>
		  <td><?php echo $this->cmsTranslator('link_entry_status');?></td>
          <td><?php if($this->Item['status'] == 1){
          		echo $this->cmsIconButton('Active', HTTP_IMAGES . '/icon/icon_16_active.png');
          	  }else{
          		echo $this->cmsIconButton('Inactive', HTTP_IMAGES . '/icon/icon_16_inactive.png');
          	  }?></td>
        </tr>
      </table>
    </form>
</div>
</div>