<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/article/sectionnew")?>">Section New</a><br>
	<a href="<?php echo $this->baseUrl("/admin/article/sectionedit")?>">Section Edit</a><br>	
	<a href="<?php echo $this->baseUrl("/admin/article/sectionmanager")?>">Section Manager</a><br>
	<?php echo new Admin_Form_SectionManager();?>
</div>
<h4>Section Manager {By DungDV}</h4>
