<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/category/categorynew")?>">Category New</a><br>
	<a href="<?php echo $this->baseUrl("/admin/category/categoryedit")?>">Category Edit</a><br>	
	<a href="<?php echo $this->baseUrl("/admin/category/categorymanager")?>">Category Manager</a><br>
</div>
<h4>Category Manager{By DungDV}</h4>
<?php echo new Admin_Form_CategoryManager();?>
<table border="1">
	<tr>
		<th width="5%">#</th>
		<th width="10%">Check</th>
		<th width="30%" class="title">Title</th>
		<th width="10%">Published</th>
		<th width="15%">Access Level</th>
		<th width="15%">Section</th>
		<th width="20%">ID</th>
	</tr>
	<tbody>
		<tr class="row0">
			<td width="5%" align="center">1</td>
			<td width="10%" align="center"><input type="radio" id="cb0" name="cid[]"
				value="en-GB" onclick="isChecked(this.checked);" /></td>
			<td width="25%">Name of Category</td>
			<td width="5%" align="center">&nbsp;</td>
			<td align="center">Admin</td>
			<td align="center">Name of Section</td>
			<td align="center">SE001</td>
		</tr>
		
	</tbody>

</table>