<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/category/categorynew")?>">Category New</a><br>
	<a href="<?php echo $this->baseUrl("/admin/category/categoryedit")?>">Category Edit</a><br>	
	<a href="<?php echo $this->baseUrl("/admin/category/categorymanager")?>">Category Manager</a><br>
	<a href="<?php echo $this->baseUrl("/admin/category/frontpagemanager")?>">Front Page Manager</a><br>
</div>
<h4>Front Page Manager {By DungDV}</h4>
<?php echo new Admin_Form_FrontPageManager();?>
