<div id="admin_control">
	<div id="admin_menu">
		<ul>
			<li><a href="<?php echo $this->baseUrl("/admin/login")?>">Login</a></li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/config")?>">
					<img alt="Configuration" src="/Zend/cms/public/skins/admin/default/image/icon-config.png">
					<br><span>Configuration</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/user")?>">
					<img alt="User" src="/Zend/cms/public/skins/admin/default/image/icon-user.png">
					<br><span>User Manager</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/menu")?>">
					<img alt="Menu" src="/Zend/cms/public/skins/admin/default/image/icon-menu.png">
					<br><span>Menu Manager</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/article")?>">
					<img alt="Article" src="/Zend/cms/public/skins/admin/default/image/icon-article.png">
					<br><span>Article Manager</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/category")?>">
					<img alt="Category" src="/Zend/cms/public/skins/admin/default/image/icon-category.png">
					<br><span>Category Manager</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/media")?>">
					<img alt="Media" src="/Zend/cms/public/skins/admin/default/image/icon-media.png">
					<br><span>Media Manager</span>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->baseUrl("/admin/language")?>">
					<img alt="Language" src="/Zend/cms/public/skins/admin/default/image/icon-language.png">
					<br><span>Language Manager</span>
				</a>
			</li>
		</ul>
	</div>
	<div id="admin_info">
		<h3>Welcome to Click and Change</h3>
	</div>
</div>




