<div id="content">

	<div class="toolbox">
		<div class="left">Quản Lý:Sản Phẩm</div>
		<div class="right">
			<div><a href="<?php echo $this->baseUrl("/admin/products/productnew")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-new.png';?>"/><br>New</a></div>
			<div><a href="<?php echo $this->baseUrl("/admin/products/productedit")?>"><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-inactive.png';?>"/><br>Edit</a></div>
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-active.png';?>"/><br>Active</a></div>			
			<div><a href=""><img alt="" src="<?php echo HTTP_IMAGES . '/icon/icon-32-delete.png';?>"/><br>Delete</a></div>
		</div>
	</div>
	<div class="breadcrumb">
		<a href="#">...</a>
		<a href="#">...</a>
	</div>
	<div id="main">
<h1>Sản Phẩm</h1>
     <table class="list">
     <thead>
     <tr>
     	<td class="center"><input id="Checkbox1" type="checkbox" /></td>
		<td class="center">Mã</td>
		<td class="center">Tên Sản Phẩm</td>
		<td class="center">Giá</td>
		<td class="center">Hình Ảnh</td>
		<td class="center">&nbsp;</td>
		<td class="center">&nbsp;</td>
	</tr>
	</thead>
	<?php foreach ($this->products as $product) { ?>
	<tr class="row">
		<td class='center'><input id="Checkbox2" type="checkbox" /></td>
		<td class='center'>
			<?php echo $product['product_id'];?>
		</td>
		<td class='center'>
			<?php echo $product['name'];?>
		</td>
		<td class='center'>
			<?php echo $product['price'];?>
		</td>
		<td class='center'>
			<img src="<?php echo HTTP_IMAGES . '/' . $product['image'];?>" width="50px" height="50px"/>
		</td>
		<td class='center'>
			<a href="<?php echo $this->baseUrl("/admin/products/edit")?>/id/<?php echo $product['product_id'];?>">Sửa</a>
		</td>
		<td class='center'>
			<a onclick="alert('Bạn có muốn xóa các sản phẩm có id là:<?php echo $product['product_id'];?>');" href="<?php echo $this->baseUrl(); ?>/admin/products/delete/id/<?php echo $product['product_id'];?>">Xóa</a>
		</td>
	</tr>
	<?php }?>
		<tr class='row'>
			<td colspan='7' class='center'><?php echo implode($this->pageLink, $this->seperator)?></td>
		</tr>
	</table>
	<div ></div>
</div>
</div>


