<ul id="admin_menu">
<li><a href="<?php echo $this->baseUrl("/admin/login")?>">Login</a>{designed by LinhTA}</li>
<li><a href="<?php echo $this->baseUrl("/admin/config")?>">Configuration</a>{designed by ThaoNX}</li>
<li><a href="<?php echo $this->baseUrl("/admin/user")?>">User Manager</a>{designed by ThanhCV}</li>
<li><a href="<?php echo $this->baseUrl("/admin/menu")?>">Menu Manager</a>{designed by ThanhCV}</li>
<li><a href="<?php echo $this->baseUrl("/admin/acticle")?>">Acticle Manager</a></li>
<li><a href="<?php echo $this->baseUrl("/admin/category")?>">Category Manager</a></li>
<li><a href="<?php echo $this->baseUrl("/admin/media")?>">Media Manager</a></li>
<li><a href="<?php echo $this->baseUrl("/admin/language")?>">Language Manager</a> {designed by LinhTA}</li>
</ul>





