<ul id="admin_menu">
<li><a href="<?php echo $this->baseUrl("/admin/login")?>">Login</a>{by LinhTA}</li>
<li><a href="<?php echo $this->baseUrl("/admin/config")?>">Configuration</a>{ by ThaoNX}</li>
<li><a href="<?php echo $this->baseUrl("/admin/user")?>">User Manager</a>{ by ThanhCV}</li>
<li><a href="<?php echo $this->baseUrl("/admin/menu")?>">Menu Manager</a>{ by ThanhCV}</li>
<li><a href="<?php echo $this->baseUrl("/admin/article")?>">Article Manager</a>{by TuTM + DucNH}</li>
<li><a href="<?php echo $this->baseUrl("/admin/category")?>">Category Manager</a></li>
<li><a href="<?php echo $this->baseUrl("/admin/media")?>">Media Manager</a></li>
<li><a href="<?php echo $this->baseUrl("/admin/language")?>">Language Manager</a> {by LinhTA}</li>
</ul>





