<div id="content">
  <div class="breadcrumb"></div>
  <?php if(isset($_SESSION['editmode'])) if($_SESSION['editmode'] == 'ON'){?>
  	<script>
		
  	</script>
  <?php }?>

  <?php if ($this->Item) { ?>
  <div class="news-info">
    <div>
      <div class="title"><?php echo $this->Item['title']; ?></div>
      <div class="summary"><?php echo html_entity_decode($this->Item['summary'], ENT_QUOTES, 'UTF-8'); ?></div>
      <div class="description"><?php echo html_entity_decode($this->Item['description'], ENT_QUOTES, 'UTF-8'); ?></div>
    </div>
    <?php } ?>
  </div>
</div>