<!-- HIỂN THỊ DANH SÁCH VÀ CÁC THAO TÁC CĂN BẢN TRÊN DANH SÁCH -->
<div id="content">
<div class="toolbox">
	<div class="left"><?php echo $this->Title?></div>
	<?php
		//1. Add new - link
		$btnAddNew = $this->cmsButton(
						'Add new',
						$this->baseUrl($this->currentController . '/add'),
						HTTP_IMAGES . '/icon/icon-32-new.png',
						'link'
					);
		//2. Active - submit
		$btnActive = $this->cmsButton(
						'Active Items',
						$this->baseUrl($this->currentController . '/status/type/1'),											
						HTTP_IMAGES . '/icon/icon-32-active.png',
						'submit'
					);
		//3. Inactive- submit
		$btnInactive = $this->cmsButton(
						'Inactive Items',
						$this->baseUrl($this->currentController . '/status/type/0'),										
						HTTP_IMAGES . '/icon/icon-32-inactive.png',
						'submit'
					);
		
	?>
	<div class="right"><?php echo $btnAddNew;?><?php echo $btnActive;?><?php echo $btnInactive;?></div>
</div>
<div class="breadcrumb">
	<!-- Thêm các breadcrumb với đường link để truy cập dể dàng hơn -->
	<a href="#">Tên số 1</a>
	<a href="#">Tên số 2</a>
	<!-- Hết breadcrumb -->
</div>
<div class="content">
    <form action="" method="post" enctype="multipart/form-data" id="form" name="form" >
      <table class="list">
        <thead>
          <tr>
            <!-- Số cột tùy biến, muốn hiện nội dung gì thì tạo cột đó -->
            <td width="1" style="text-align: center;">
            	<input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" />
            </td>            
            <td>Tên Cột 1</td>
            <td>Tên Cột 2</td>
            <td>Tên Cột 3</td>
            <td>Tên Cột 4</td>
            <td>Tên Cột 5</td>
            <td>Tên Cột 6</td>
            <td>Tên Cột 7</td>
          </tr>
        </thead>
        <tbody>
          <!-- Vòng lặp giá trị để show ra tất cả các kết quả -->
          <tr>            
            <td><!-- Cột chứ text input với giá trị là id của record --></td>
            <td>Giá trị cột 1</td>
            <td>Giá trị cột 2</td>
            <td>Giá trị cột 3</td>
            <td>Giá trị cột 4</td>
            <td>Giá trị cột 5</td>
            <td>Giá trị cột 6</td>
 			<td><!-- Mục điều khiển --></td>
          </tr>
          <!-- Ngược lại không có giá trị hiện phía dưới -->
          <tr>
            <td class="center" colspan="8">Không có kết quả</td>
          </tr>
          <!-- Kết thúc -->
        </tbody>
      </table>
    </form>
</div>
</div>