<script>
	var cofirm = false;
	var selected_id;
	
	function deleteCategory(id) {
		cofirm = false;
		selected_id = id;
		$("#cofirm-delete-category").dialog("open");
	}

	$(".btnEdit").button();
	$(".btnDel").button();
	function editCategory(id) {
		selected_id = id;
		$("#edit-category-form").dialog("open");
		$("#edit-category-form-content").html("Loading...");
		$.ajax({
			type: 'POST',
			url: '<?php echo HTTP_SERVER."front/category/edit"?>',
			data: {
				id: selected_id
			},
			success: function(data) {
				$("#edit-category-form-content").html(data);
			},
			error: function(request, textStatus, error) {
				showMessage("Error! <br> Detail: <br>" + request.responseText + error);
			}	
		});
		$(this).dialog("close");
	}

	$(function() {
		$("#cofirm-delete-category").dialog({
			autoOpen: false,
			width: 300,
			height: 150,
			modal: true,
			buttons: {
				"Yes": function() {
					$.ajax({
						type: 'POST',
						url: '<?php echo HTTP_SERVER."front/category/delete"?>',
						data: {
							id: selected_id
						},
						success: function(data) {
							$("#row" + selected_id).remove();
						},
						error: function(request, error) {
							showMessage("Error! <br> Detail: <br>" + request.responseText);
						}	
					});
					$(this).dialog("close");
				},
				"No": function() {
					$(this).dialog("close");
				}
			}
		});
	});
</script>

<div id="cofirm-delete-category" title="CMS Click and Change">
	Do you want to delete this category?
</div>
<h3>Category List</h3>
<table class="list" width="" cellpadding="1" cellspacing="0">

	<thead>
		<tr>
			<td align="center">Name</td>			
			<td align="center">Action</td>
		</tr>
	</thead>
	<tbody>
	<?php
		foreach($this->items as $category) {
			showMenuRow($category);
		}
	?>
	</tbody>
</table>

<?php
function showMenuRow($category) {
	echo '<tr id="row'.$category['category_id'].'">';
    echo '<td>' . $category['name'];
?>
	<td align="center">
		<a class="btnEdit" onclick="editCategory('<?php echo $category['category_id'];?>');">Edit</a>
		<?php if($category['name']!="Home Page") {?>
		<a class="btnDel" onclick="deleteCategory('<?php echo $category['category_id'];?>');">Del</a>
		<?php }?>
	</td></tr>
<?php
}
?>