<h4>Menu Manager </h4>
<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/menu/menuedit")?>">Menu Item Edit</a><br>
	<a href="<?php echo $this->baseUrl("/admin/menu/menumanager")?>">Menu Manager</a>{by ThiVT}<br>
	<a href="<?php echo $this->baseUrl("/admin/menu/menuitemmanager")?>">Menu Item Manager</a>{by ThiVT}<br>
	<a href="<?php echo $this->baseUrl("/admin/menu/menutrash")?>">Menu Trash</a><br>
</div>