<div style="text-align: left">
	<a href="<?php echo $this->baseUrl("/admin/menu")?>">Menu Manager</a><br>	
</div>
<h4>Menu Item Edit( by ThiVT) </h4>
<form method="post" name="menumanagerForm">
	 <table border="1" align="right">
		<tr>
			<td align="right"><input align="right" type="button" name="btnMenus" id="btnCopy" onClick="window.location.href = '<?php echo $this->baseUrl("/admin/menu")?>'" value="Menus" />
			<input align="right" type="button" name="btnDefault" id="btnDefault" value="Default" />
			<input align="right" type="button" name="btnPublish" id="btnPublish"  value="Publish" />
			<input align="right" type="button" name="btnUnpublish" id="btnUnpublish" value="Unpublish" />	
			<input align="right" type="button" name="btnMove" id="btnMove" value="Move" />	
			<input align="right" type="button" name="btnCopy" id="btnCopy" value="Copy" />	
			<input align="right" type="button" name="btnTrash" id="btnTrash" value="Trash" />	
			<input align="right" type="button" name="btnEdit" id="btnEdit" value="Edit" />	
			<input align="right" type="button" name="btnNew" id="btnNew" value="New" />				
			<input align="right" type="button" name="btnHelp" id="btnHelp" value="Help" /></td>
		</tr>
  </table><br><br>
   <table align="Left">
		<tr>
			<td align="right">
			Filter:<input type="text" name="fkeyword" />			
			<input align="right" type="submit" name="btnNew" id="btnNew" value=" Go " />			
			<input align="right" type="button" name="btnHelp" id="btnHelp" value="Reset" /></td>
		</tr>
  </table><br><br>
<table border="1">
	<tr>
		<th width="3%">#</th>
		<th width="3%">&nbsp;</th>
		<th width="20%">Menu item</th>
		<th width="7%">Default</th>
		<th width="7%">Published</th>
		<th width="15%">Order</th>
		<th width="10%">Access Level</th>
		<th width="15%">Type</th>		
		<th width="5%">ID</th>
	</tr>
	<tbody>
		<tr class="row0">
			<td width="3%">1</td>
			<td width="3%"><input type="checkbox" id="cb0" name="cid[]"
				value="en_GB" onclick="isChecked(this.checked);"/></td>
			<td width ="10%" align="center">Menu item 1</td>
			<td width ="10%" align="center">Yes</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">1</td>
			<td width ="10%" align="center">Public</td>
			<td width ="10%" align="center">Articles->Front Page</td>			
			<td width ="10%" align="center">1</td>
		</tr>
		<tr class="row0">
			<td width="3%">2</td>
			<td width="3%"><input type="checkbox" id="cb0" name="cid[]"
				value="en_GB" onclick="isChecked(this.checked);"/></td>
			<td width ="10%" align="center">Menu item 2</td>
			<td width ="10%" align="center">No</td>
			<td width ="10%" align="center">2</td>
			<td width ="10%" align="center">2</td>
			<td width ="10%" align="center">Private</td>			
			<td width ="10%" align="center">Articles->Front Page</td>
			<td width ="10%" align="center">3</td>
		</tr>
	</tbody>
</table>
<div align="center">Display #
<select name="displayItems">
<option value="20">20</option>
<option value="30">30</option>
<option value="40">40</option>
</select>
</div>
</form>